import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { activeHost } from '../api/config.ts';
import { createApiClient } from '../api/client.ts';
import { resolveProjectContext } from '../command-helpers.ts';
import { connectorProjectContext } from '../connector-gateway/gateway.ts';
import { resolveProjectId } from '../project-link.ts';

// These tests pin the contract the platform relies on when it injects auth
// into a session sandbox: KORTIX_TOKEN carries the session connector PAT,
// KORTIX_API_URL already includes the `/v1` mount, and
// KORTIX_PROJECT_ID selects the project — all read with zero config files.

const ENV_KEYS = [
  'KORTIX_TOKEN',
  'KORTIX_TOKEN',
  'KORTIX_API_URL',
  'KORTIX_PROJECT_ID',
  'BASH_ENV',
  'KORTIX_DISABLE_SANDBOX_ENV_FILE',
  'KORTIX_CONFIG_FILE',
  'KORTIX_AUTH_FILE',
] as const;

let saved: Record<string, string | undefined>;

beforeEach(() => {
  saved = {};
  for (const k of ENV_KEYS) {
    saved[k] = process.env[k];
    delete process.env[k];
  }
  // Point config storage at a path that does not exist so no real auth leaks in.
  process.env.KORTIX_CONFIG_FILE = '/nonexistent/kortix-test-config.json';
  process.env.KORTIX_DISABLE_SANDBOX_ENV_FILE = '1';
});

afterEach(() => {
  for (const k of ENV_KEYS) {
    if (saved[k] === undefined) delete process.env[k];
    else process.env[k] = saved[k];
  }
});

describe('in-sandbox auth resolution', () => {
  it('uses KORTIX_TOKEN as the active token', () => {
    process.env.KORTIX_TOKEN = 'kortix_pat_cli';
    process.env.KORTIX_API_URL = 'https://tunnel.example/v1';
    const host = activeHost();
    expect(host?.token).toBe('kortix_pat_cli');
    expect(host?.url).toBe('https://tunnel.example/v1');
  });

  it('loads sandbox CLI auth from BASH_ENV agent-env.sh when non-interactive shells did not source it', () => {
    const dir = mkdtempSync(join(tmpdir(), 'kortix-cli-agent-env-'));
    const envFile = join(dir, 'agent-env.sh');
    try {
      writeFileSync(
        envFile,
        [
          '# Generated by Kortix agent sandbox session.',
          "export KORTIX_TOKEN='kortix_pat_from_file'",
          "export KORTIX_API_URL='https://dev-api.kortix.com/v1'",
          "export KORTIX_FRONTEND_URL='https://dev.kortix.com'",
          "export KORTIX_PROJECT_ID='proj-from-file'",
          "export NOT_ALLOWLISTED='must-not-be-imported'",
          "export AGENTMAIL_API_KEY='must-not-be-imported'",
          '',
        ].join('\n'),
      );
      delete process.env.KORTIX_DISABLE_SANDBOX_ENV_FILE;
      process.env.BASH_ENV = envFile;

      const host = activeHost();
      expect(host?.token).toBe('kortix_pat_from_file');
      expect(host?.url).toBe('https://dev-api.kortix.com/v1');
      expect(resolveProjectId()).toBe('proj-from-file');
      expect(connectorProjectContext().projectId).toBe('proj-from-file');
      expect(process.env.NOT_ALLOWLISTED).toBeUndefined();
      expect(process.env.AGENTMAIL_API_KEY).toBeUndefined();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('uses KORTIX_TOKEN as the single sandbox session credential', () => {
    process.env.KORTIX_TOKEN = 'kortix_pat_session';
    expect(activeHost()?.token).toBe('kortix_pat_session');
  });

  it('reads the project id from KORTIX_PROJECT_ID', () => {
    process.env.KORTIX_PROJECT_ID = 'proj-xyz';
    expect(resolveProjectId()).toBe('proj-xyz');
  });

  it('lets connector management commands override KORTIX_PROJECT_ID with --project', () => {
    process.env.KORTIX_TOKEN = 'kortix_pat_cli';
    process.env.KORTIX_API_URL = 'https://tunnel.example/v1';
    process.env.KORTIX_PROJECT_ID = 'proj-from-env';

    expect(connectorProjectContext('proj-from-flag').projectId).toBe('proj-from-flag');
  });
});

describe('env token vs .kortix/link.json host', () => {
  // A repo may carry a committed link.json naming a host (per-repo binding).
  // Inside a session sandbox that named host has no stored credentials, so
  // the platform-injected env token must outrank it — otherwise every
  // project-scoped command dies with "host not logged in".
  let dir: string;
  let savedCwd: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'kortix-cli-link-'));
    mkdirSync(join(dir, '.kortix'), { recursive: true });
    writeFileSync(
      join(dir, '.kortix', 'link.json'),
      JSON.stringify({
        project_id: 'proj-from-link',
        account_id: 'acct',
        host: 'kortix-internal-dev',
        linked_at: '2026-01-01T00:00:00.000Z',
      }),
    );
    savedCwd = process.cwd();
    process.chdir(dir);
  });

  afterEach(() => {
    process.chdir(savedCwd);
    rmSync(dir, { recursive: true, force: true });
  });

  it('resolveProjectContext uses the env token even when link.json names a host', async () => {
    process.env.KORTIX_TOKEN = 'kortix_pat_cli';
    process.env.KORTIX_API_URL = 'https://tunnel.example/v1';
    const ctx = await resolveProjectContext();
    expect(ctx).not.toBeNull();
    expect(ctx?.auth.token).toBe('kortix_pat_cli');
    expect(ctx?.auth.api_base).toBe('https://tunnel.example/v1');
    // Project still comes from the link — only the HOST binding is overridden.
    expect(ctx?.projectId).toBe('proj-from-link');
  });

  it('without an env token the link host is still honored (and fails logged-out)', async () => {
    // Config file points at a nonexistent path → the named host has no token →
    // the pre-existing behavior (refuse with "not logged in") is preserved.
    const ctx = await resolveProjectContext();
    expect(ctx).toBeNull();
  });

  it('an explicit --host override still wins over the env token', async () => {
    process.env.KORTIX_TOKEN = 'kortix_pat_cli';
    // 'nonexistent-host' has no credentials → context resolution must fail
    // rather than silently falling back to the env token the caller did not ask for.
    const ctx = await resolveProjectContext({ hostArg: 'nonexistent-host' });
    expect(ctx).toBeNull();
  });
});

describe('API URL joining', () => {
  let calls: string[];
  const realFetch = globalThis.fetch;

  beforeEach(() => {
    calls = [];
    globalThis.fetch = (async (url: string) => {
      calls.push(String(url));
      return new Response(JSON.stringify({ ok: true }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    }) as unknown as typeof fetch;
  });
  afterEach(() => {
    globalThis.fetch = realFetch;
  });

  it('does not double the /v1 mount when the base already ends in /v1', async () => {
    // This is exactly the sandbox shape: KORTIX_API_URL = https://<tunnel>/v1
    const client = createApiClient({ apiBase: 'https://tunnel.example/v1', token: 't' });
    await client.get('/projects/p1/change-requests');
    expect(calls[0]).toBe('https://tunnel.example/v1/projects/p1/change-requests');
  });

  it('adds the /v1 mount when the base is a bare origin', async () => {
    const client = createApiClient({ apiBase: 'https://api.kortix.com', token: 't' });
    await client.get('/projects/p1/change-requests');
    expect(calls[0]).toBe('https://api.kortix.com/v1/projects/p1/change-requests');
  });

  it('tolerates a trailing slash on the base', async () => {
    const client = createApiClient({ apiBase: 'https://tunnel.example/v1/', token: 't' });
    await client.get('/projects/p1/change-requests');
    expect(calls[0]).toBe('https://tunnel.example/v1/projects/p1/change-requests');
  });
});
