import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  resolveProjectContext,
  surfaceApiError,
  takeFlagBool,
  takeFlagValue,
} from '../command-helpers.ts';
import { C, help, status } from '../style.ts';
import type { ProjectSecret, ProjectSecretsResponse } from '../api/types.ts';

const HELP = help`Usage: kortix env <subcommand> [options]

Bulk transfer secrets between a local .env file and the cloud.

Subcommands:
  pull [--out <path>]              Write each cloud secret as a line in
                                   the dotenv file (defaults to ./.env).
                                   VALUES ARE NOT EXPOSED — we only have
                                   names. Each line is "NAME=" so you can
                                   fill in locally.
  push --from <path>               Upload every NAME=VALUE in the file
                                   as a project secret.

Global options:
  --project <id>     Operate on this project id (default: linked).
  --force            (pull) Overwrite an existing destination file.
  -h, --help         Show this help.

Heads-up: cloud secrets are encrypted at rest with no read API — the
plaintext never comes back to a client, and it reaches a sandbox only for a
secret whose exposure is \`environment\`. \`env pull\` therefore exports a
SKELETON (names only), not values. \`env push\` sets values; it does not
change any secret's exposure — use \`kortix secrets delivery\` for that.
`;

export async function runEnv(argv: string[]): Promise<number> {
  if (argv.length === 0 || argv[0] === '-h' || argv[0] === '--help') {
    process.stdout.write(HELP);
    return argv.length === 0 ? 2 : 0;
  }

  const sub = argv[0];
  const rest = argv.slice(1);
  let projectFlag: string | undefined;
  let hostFlag: string | undefined;
  let outFlag: string | undefined;
  let fromFlag: string | undefined;
  let force = false;
  try {
    projectFlag = takeFlagValue(rest, ['--project']);
    hostFlag = takeFlagValue(rest, ['--host']);
    outFlag = takeFlagValue(rest, ['--out', '-o']);
    fromFlag = takeFlagValue(rest, ['--from', '-f']);
    force = takeFlagBool(rest, ['--force']);
  } catch (err) {
    process.stderr.write(`${status.err((err as Error).message)}\n`);
    return 2;
  }
  const ctxOpts: CtxOpts = { projectArg: projectFlag, hostArg: hostFlag };

  switch (sub) {
    case 'pull':
      return envPull(outFlag, force, ctxOpts);
    case 'push':
      return envPush(fromFlag, ctxOpts);
    default:
      process.stderr.write(`${status.err(`unknown subcommand "${sub}"`)}\n\n${HELP}`);
      return 2;
  }
}

type CtxOpts = { projectArg?: string; hostArg?: string };

async function envPull(outArg: string | undefined, force: boolean, opts: CtxOpts): Promise<number> {
  const ctx = await resolveProjectContext(opts);
  if (!ctx) return 1;

  let resp: ProjectSecretsResponse;
  try {
    resp = await ctx.client.get<ProjectSecretsResponse>(
      `/projects/${ctx.projectId}/secrets`,
    );
  } catch (err) {
    return surfaceApiError(err);
  }

  const outPath = resolve(process.cwd(), outArg ?? '.env');
  if (!force) {
    try {
      const existing = readFileSync(outPath, 'utf8');
      if (existing.trim().length > 0) {
        process.stderr.write(
          `${status.err(`${outPath} already exists — pass --force to overwrite.`)}\n`,
        );
        return 1;
      }
    } catch {
      /* file doesn't exist — proceed */
    }
  }

  // Merge: every name in items + every required/optional → one entry.
  const names = new Set<string>();
  for (const s of resp.items) names.add(s.name);
  for (const n of resp.required) names.add(n);
  for (const n of resp.optional) names.add(n);
  const sorted = [...names].sort();

  const lines: string[] = [
    '# Generated by `kortix env pull` — fill in values locally.',
    `# Project: ${ctx.projectId}`,
    `# ${new Date().toISOString()}`,
    '',
  ];
  for (const name of sorted) {
    const spec = resp.required.includes(name)
      ? 'required'
      : resp.optional.includes(name)
        ? 'optional'
        : 'set in cloud';
    lines.push(`# ${spec}`);
    lines.push(`${name}=`);
  }

  writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
  process.stdout.write(
    `${status.ok(`Wrote ${C.bold}${sorted.length}${C.reset} variable name${sorted.length === 1 ? '' : 's'} to ${outPath}`)}\n`,
  );
  process.stdout.write(`${C.dim}  Values are not exported — see \`kortix env push --from .env\` to upload.${C.reset}\n`);
  return 0;
}

async function envPush(fromArg: string | undefined, opts: CtxOpts): Promise<number> {
  if (!fromArg) {
    process.stderr.write(`${status.err('Pass --from <dotenv-path>.')}\n`);
    return 2;
  }
  const ctx = await resolveProjectContext(opts);
  if (!ctx) return 1;

  const srcPath = resolve(process.cwd(), fromArg);
  let raw: string;
  try {
    raw = readFileSync(srcPath, 'utf8');
  } catch (err) {
    process.stderr.write(`${status.err(`Cannot read ${srcPath}: ${(err as Error).message}`)}\n`);
    return 1;
  }

  const pairs = parseDotenv(raw);
  if (pairs.length === 0) {
    process.stderr.write(`${status.err(`No NAME=VALUE pairs found in ${srcPath}.`)}\n`);
    return 1;
  }

  let okCount = 0;
  for (const p of pairs) {
    try {
      await ctx.client.post<ProjectSecret>(
        `/projects/${ctx.projectId}/secrets`,
        { name: p.name, value: p.value },
      );
      okCount += 1;
      process.stdout.write(`${status.ok(`${C.bold}${p.name}${C.reset}`)}\n`);
    } catch (err) {
      surfaceApiError(err);
      process.stderr.write(`  ${C.dim}└─ for ${p.name}${C.reset}\n`);
    }
  }
  process.stdout.write(`\n  ${C.dim}${okCount}/${pairs.length} uploaded from ${srcPath}${C.reset}\n\n`);
  return okCount === pairs.length ? 0 : 1;
}

/** Minimal dotenv parser. Supports `NAME=VALUE` and `export NAME=VALUE`,
 *  optional matching single/double quotes around the value, `#` line
 *  comments, blank lines. Skips entries with empty values. */
function parseDotenv(text: string): { name: string; value: string }[] {
  const out: { name: string; value: string }[] = [];
  for (const lineRaw of text.split(/\r?\n/)) {
    const line = lineRaw.trim();
    if (!line || line.startsWith('#')) continue;
    const stripped = line.replace(/^export\s+/, '');
    const eq = stripped.indexOf('=');
    if (eq <= 0) continue;
    const name = stripped.slice(0, eq).trim();
    let value = stripped.slice(eq + 1).trim();
    if (!value) continue;
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out.push({ name, value });
  }
  return out;
}
