/**
 * Kortix project starter — folder-based template.
 *
 * The starter is a shared base directory plus optional template layers.
 * `getStarterFiles()` walks the selected directories, applies `{{var}}`
 * substitutions, and returns `[{ path, content }]` so callers (the
 * API's create-repo flow, the `kortix init` CLI) can do whatever they
 * want with the result — commit to GitHub, write to disk, render a
 * preview.
 *
 * Editing the starter is plain file editing — shared Kortix runtime
 * files live under `templates/base/`, richer starter layers live under
 * `templates/<template>/`, optional first-party marketplace items live
 * under `templates/marketplace/`, and both the API and CLI pick them up.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

// Static JSON snapshot of the template tree, regenerated by
// `scripts/generate-embedded.ts`. The on-disk template walk below is the
// source of truth in a source checkout (so editing a template just works),
// but it does not survive `bun build --compile`; this snapshot is inlined
// into the compiled binary and used as a fallback when the files are absent.
import embeddedStarter from './embedded.generated.json' with { type: 'json' };

const EMBEDDED_STARTER = embeddedStarter as Record<string, { files: StarterFile[] }>;

export interface StarterFile {
  /** Repo-relative path (POSIX-separated, no leading slash). */
  path: string;
  /** UTF-8 content with `{{var}}` placeholders resolved. */
  content: string;
}

// There is one USER-FACING starter kit:
// - `general-knowledge-worker`: the full skill kit on the OpenCode REST runtime.
//
// `minimal` (base only, no domain skills) is kept purely as an INTERNAL
// building block: the project-clone seed path (`buildProjectSeedFilesFromItem`)
// uses it to lay down the OpenCode runtime floor and canonical skill source
// before a `registry:project`'s own skills/agents are layered on top, so a
// specialized project template isn't
// polluted with every general-knowledge skill. It is not surfaced in the
// create-project UI, mobile, or the `kortix init` prompt.
//
export const STARTER_TEMPLATE_IDS = [
  'minimal',
  'general-knowledge-worker',
] as const;
export type StarterTemplateId = (typeof STARTER_TEMPLATE_IDS)[number];
export const DEFAULT_STARTER_TEMPLATE_ID: StarterTemplateId = 'general-knowledge-worker';

export const KORTIX_MANAGED_SKILL_NAMES = [
  'kortix-cli',
  'kortix-computer',
  'kortix-connectors',
  'kortix-marketplace',
  'kortix-voice',
  'kortix-memory',
  'kortix-onboarding',
  'kortix-slack',
  'kortix-system',
  'kortix-teams',
] as const;
export type KortixManagedSkillName = (typeof KORTIX_MANAGED_SKILL_NAMES)[number];

const KORTIX_MANAGED_SKILL_NAME_SET = new Set<string>(KORTIX_MANAGED_SKILL_NAMES);

export function isKortixManagedSkillName(name: string): name is KortixManagedSkillName {
  return KORTIX_MANAGED_SKILL_NAME_SET.has(name);
}

export interface StarterVars {
  /** Human display name for the project (e.g. "Company OS"). */
  projectName: string;
  /** "owner/repo" GitHub identifier. Optional — defaults to "your-org/your-repo". */
  repoFullName?: string;
  /** Starter kit. Defaults to `general-knowledge-worker`.
   *  `minimal` is an internal base-only build. */
  template?: StarterTemplateId;
}

/** Absolute path to the bundled base template directory. */
const BASE_TEMPLATE_DIR = join(import.meta.dir, '..', 'templates', 'base');
const GENERAL_KNOWLEDGE_WORKER_TEMPLATE_DIR = join(
  import.meta.dir,
  '..',
  'templates',
  'general-knowledge-worker',
);
const MARKETPLACE_TEMPLATE_DIR = join(import.meta.dir, '..', 'templates', 'marketplace');
const MANAGED_TEMPLATE_DIR = join(import.meta.dir, '..', 'templates', 'managed');

/** Roots that may legitimately hold nothing — see `rawFilesForRoot`. */
const OPTIONAL_TEMPLATE_ROOTS = new Set(['marketplace-projects']);

// Build artifacts and OS cruft that can appear in a working tree but must never
// be scaffolded into a user's repo. This MUST stay in sync with the identical
// lists in `scripts/generate-embedded.ts`: the compiled binary reads the
// snapshot (which the generator already filters) while a source checkout walks
// disk here, so a filter in only one place means the two paths scaffold
// different files. That drift is exactly how three `__pycache__/*.pyc` files
// ended up committed into every API-created project.
const IGNORED_TEMPLATE_DIRS = new Set([
  '.cache',
  '.mypy_cache',
  '.pytest_cache',
  '.ruff_cache',
  '.tox',
  '.venv',
  '__pycache__',
  'node_modules',
]);
const IGNORED_TEMPLATE_FILES = new Set(['.DS_Store', 'Thumbs.db']);
const MARKETPLACE_PROJECTS_TEMPLATE_DIR = join(
  import.meta.dir,
  '..',
  'templates',
  'marketplace-projects',
);

export function normalizeStarterTemplateId(value: unknown): StarterTemplateId {
  if (typeof value === 'string' && (STARTER_TEMPLATE_IDS as readonly string[]).includes(value)) {
    return value as StarterTemplateId;
  }
  return DEFAULT_STARTER_TEMPLATE_ID;
}

const GENERAL_KNOWLEDGE_WORKER_SKILLS_PREFIX = '.kortix/opencode/skills/';

export function listGeneralKnowledgeWorkerSkills(): string[] {
  const skillsDir = join(GENERAL_KNOWLEDGE_WORKER_TEMPLATE_DIR, '.kortix', 'opencode', 'skills');
  try {
    return readdirSync(skillsDir)
      .filter((entry) => statSync(join(skillsDir, entry)).isDirectory())
      .sort((a, b) => a.localeCompare(b));
  } catch {
    // Compiled binary: derive the skill directory names from the embedded
    // snapshot instead of the (absent) on-disk template tree.
    const names = new Set<string>();
    for (const file of EMBEDDED_STARTER['general-knowledge-worker']?.files ?? []) {
      if (!file.path.startsWith(GENERAL_KNOWLEDGE_WORKER_SKILLS_PREFIX)) continue;
      const rest = file.path.slice(GENERAL_KNOWLEDGE_WORKER_SKILLS_PREFIX.length);
      const top = rest.split('/')[0];
      if (top) names.add(top);
    }
    return [...names].sort((a, b) => a.localeCompare(b));
  }
}

/**
 * Walk the base template and return every file with `{{var}}`
 * placeholders resolved. Output is sorted by path for stable commit
 * ordering — both the API and CLI rely on that.
 */
export function getStarterFiles(vars: StarterVars): StarterFile[] {
  const resolvedVars: Required<StarterVars> = {
    projectName: vars.projectName,
    repoFullName: vars.repoFullName ?? 'your-org/your-repo',
    template: normalizeStarterTemplateId(vars.template),
  };

  // Later roots win (`byPath.set`), so the general-knowledge-worker layer may
  // override a base file of the same path.
  const roots: { name: string; dir: string }[] = [{ name: 'base', dir: BASE_TEMPLATE_DIR }];
  if (resolvedVars.template !== 'minimal') {
    roots.push({
      name: 'general-knowledge-worker',
      dir: GENERAL_KNOWLEDGE_WORKER_TEMPLATE_DIR,
    });
  }

  const byPath = new Map<string, StarterFile>();
  for (const root of roots) {
    for (const raw of rawFilesForRoot(root.name, root.dir)) {
      byPath.set(raw.path, { path: raw.path, content: interpolate(raw.content, resolvedVars) });
    }
  }

  const files = [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path));
  return files;
}

/**
 * The managed `kortix-*` family — everything the platform guarantees to every
 * session regardless of what a project repo contains.
 *
 * These are deliberately NOT part of `getStarterFiles()`: the sandbox image
 * bakes them to `/opt/kortix/managed-skills` (via
 * `scripts/write-managed-skills.ts`) and the agent server force-overlays them
 * into every session at boot (`ensureInjectedManagedSkills`), so committing a
 * second copy into each project repo bought nothing — the injected body always
 * won — while padding every new project with ~10 files the user never asked
 * for and can't meaningfully edit.
 *
 * `kortix-cli` is the deliberate exception: it stays in `templates/base/` as
 * the visible front door to this family, so a fresh repo still shows the one
 * skill that explains how to reach all the others.
 */
export function getManagedSkillFiles(): StarterFile[] {
  return rawFilesForRoot('managed', MANAGED_TEMPLATE_DIR).sort((a, b) =>
    a.path.localeCompare(b.path),
  );
}

/**
 * Optional first-party items that are listed in the Kortix marketplace but are
 * not part of the starter floor.
 */
export function getMarketplaceFiles(): StarterFile[] {
  return rawFilesForRoot('marketplace', MARKETPLACE_TEMPLATE_DIR).sort((a, b) =>
    a.path.localeCompare(b.path),
  );
}

/**
 * Full, clonable example Kortix projects listed in the marketplace under
 * `registry:project`. Each is a subdirectory keyed by slug (e.g.
 * `marketplace-projects/support-agent-kit/...`); paths returned here are
 * still slug-prefixed — callers that turn this into registry items strip the
 * slug to get each project's own repo-relative paths. Raw (uninterpolated) —
 * `{{var}}` placeholders are resolved by the installer at clone time using
 * the real destination project's name, not this fixture's.
 */
export function getProjectTemplateFiles(): StarterFile[] {
  return rawFilesForRoot('marketplace-projects', MARKETPLACE_PROJECTS_TEMPLATE_DIR).sort((a, b) =>
    a.path.localeCompare(b.path),
  );
}

/**
 * Map of every bundled-catalog file path → its real repo-relative source path
 * (under `packages/starter/templates/`). Lets the marketplace build a "View
 * source" link for a first-party skill/agent/tool without guessing which
 * template root it came from. Precedence matches the catalog build
 * (base < general-knowledge-worker < managed < marketplace) so an overridden
 * file resolves to the root that actually wins.
 */
export function getStarterCatalogSourceMap(): Map<string, string> {
  const roots: Array<{ name: string; dir: string }> = [
    { name: 'base', dir: BASE_TEMPLATE_DIR },
    { name: 'general-knowledge-worker', dir: GENERAL_KNOWLEDGE_WORKER_TEMPLATE_DIR },
    { name: 'managed', dir: MANAGED_TEMPLATE_DIR },
    { name: 'marketplace', dir: MARKETPLACE_TEMPLATE_DIR },
  ];
  const map = new Map<string, string>();
  for (const root of roots) {
    for (const file of rawFilesForRoot(root.name, root.dir)) {
      map.set(file.path, `packages/starter/templates/${root.name}/${file.path}`);
    }
  }
  return map;
}

/**
 * Raw (uninterpolated) files for one template root. Walks the directory on
 * disk; if that is unavailable — the compiled `kortix` binary, where the
 * template tree was never embedded into `$bunfs` — falls back to the static
 * snapshot inlined at build time.
 */
function rawFilesForRoot(name: string, dir: string): StarterFile[] {
  try {
    return walk(dir).map((absPath) => ({
      path: relative(dir, absPath).split(sep).join('/'),
      content: readFileSync(absPath, 'utf8'),
    }));
  } catch {
    const embedded = EMBEDDED_STARTER[name];
    if (!embedded) {
      // An OPTIONAL root that is legitimately empty (git does not track empty
      // directories, so retiring every item under it removes the root outright)
      // must degrade to "no files", not take down the whole catalog build. Only
      // a root the scaffold actually needs is worth throwing over.
      if (OPTIONAL_TEMPLATE_ROOTS.has(name)) return [];
      throw new Error(`starter template "${name}" is unavailable on disk and not embedded`);
    }
    return embedded.files;
  }
}

/**
 * Replace `{{name}}` placeholders. Only `\w+` identifiers — keeps
 * accidental matches in code/docs (e.g. `{{ body.action }}` in a
 * trigger prompt) from being treated as substitution targets. Exported so
 * other callers with their own `{{var}}` content (e.g. the API's
 * `registry:project` clone path in `apps/api/src/projects/seed-files.ts`)
 * reuse this exact convention instead of reimplementing the regex.
 */
export function interpolateVars(input: string, vars: Record<string, string>): string {
  return input.replace(/\{\{(\w+)\}\}/g, (match, name: string) => {
    if (name in vars) return vars[name]!;
    return match; // leave unknown placeholders intact
  });
}

function interpolate(input: string, vars: Required<StarterVars>): string {
  return interpolateVars(input, vars as unknown as Record<string, string>);
}

function walk(root: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(root)) {
    if (IGNORED_TEMPLATE_DIRS.has(entry) || IGNORED_TEMPLATE_FILES.has(entry)) continue;
    const abs = join(root, entry);
    const st = statSync(abs);
    if (st.isDirectory()) out.push(...walk(abs));
    else if (st.isFile()) out.push(abs);
  }
  return out;
}
