// Main exports
export { createDb, type Database } from './client';
export * as schema from './schema';

// Re-export frequently used schemas and types for convenience
export {
  // Schema namespace
  kortixSchema,
  // Enums
  sandboxStatusEnum,
  projectStatusEnum,
  projectSessionStatusEnum,
  sessionLifecycleCommandStatusEnum,
  projectRoleEnum,
  projectAccessRequestStatusEnum,
  apiKeyStatusEnum,
  apiKeyTypeEnum,
  connectorAuthorizationStrategyEnum,
  // Kortix tables — accounts
  accounts,
  accountMembers,
  accountMemberships,
  accountInvitations,
  accountGithubInstallations,
  accountGithubInstallationStates,
  accountRoleEnum,
  accountsRelations,
  accountMembersRelations,
  accountGithubInstallationsRelations,
  auditEvents,
  auditSessionSequences,
  usageEvents,
  gatewayRequestLogs,
  gatewayApiKeys,
  gatewayBudgets,
  gatewayOtelConfigs,
  // Kortix tables
  projects,
  projectGitConnections,
  projectGitCredentials,
  projectMembers,
  projectAccessRequests,
  projectSecrets,
  projectSessionSecretHandles,
  projectSecretHandleStatusEnum,
  projectSecretConsumerEnum,
  secretShareScopeEnum,
  secretGrantPrincipalEnum,
  projectSecretScopeEnum,
  projectTriggerRuntime,
  projectTriggerSessionAccessGrants,
  projectTriggerExecutions,
  projectMonitorEvents,
  projectMonitorBoxes,
  sessionLifecycleCommands,
  chatChannelBindings,
  chatInstalls,
  chatPendingAuthMessages,
  chatThreads,
  chatThreadParticipants,
  chatTurnStreams,
  voiceCallTurns,
  voiceCallReadCursors,
  voiceJoinLinks,
  teamsPendingUploads,
  chatEventDedup,
  chatUserIdentities,
  projectSessions,
  projectSessionRuntimeContexts,
  accountModelPreferences,
  projectLlmRoutingPolicies,
  projectSessionGrants,
  projectSessionPublicShares,
  projectSessionVisibilityEnum,
  projectSnapshotBuilds,
  providerTransitions,
  providerTransitionStatusEnum,
  sandboxTemplates,
  sessionEnvironments,
  sessionSandboxes,
  sessionSandboxStatusEnum,
  sessionTurns,
  sessionTranscriptMirrors,
  sessionTranscriptMessages,
  sessionRuntimeProjections,
  providerEvents,
  sandboxes,
  sandboxMembers,
  legacySandboxMigrations,
  sunaAccountMigrations,
  kortixApiKeys,
  accountTokens,
  workerLeaderLease,
  // Relations
  projectsRelations,
  projectGitConnectionsRelations,
  projectGitCredentialsRelations,
  projectMembersRelations,
  projectSecretsRelations,
  projectSessionsRelations,
  projectSessionRuntimeContextsRelations,
  sandboxesRelations,
  sandboxMembersRelations,
  kortixApiKeysRelations,
  // Billing / Credits (moved from public → kortix schema)
  billingCustomers,
  creditAccounts,
  creditLedger,
  creditUsage,
  accountDeletionRequests,
  creditPurchases,
  // Billing v2 — per-seat + compute metering + per-member YOLO
  sandboxComputeSessions,
  apps,
  appAccessGrants,
  appArtifacts,
  appDeployments,
  appRuntimes,
  appDeploymentEvents,
  sessionPendingQuestions,
  yoloMemberTokens,
  stripeWebhookEventsProcessed,
  // Tunnel
  tunnelStatusEnum,
  tunnelCapabilityEnum,
  tunnelPermissionStatusEnum,
  tunnelPermissionRequestStatusEnum,
  tunnelConnections,
  tunnelPermissions,
  tunnelPermissionRequests,
  tunnelAuditLogs,
  tunnelRpcForwards,
  tunnelDeviceAuthStatusEnum,
  tunnelDeviceAuthRequests,
  tunnelConnectionsRelations,
  tunnelPermissionsRelations,
  tunnelPermissionRequestsRelations,
  tunnelAuditLogsRelations,
  // OAuth2 Provider
  oauthClients,
  oauthAuthorizationRequests,
  oauthConsents,
  oauthAuthorizationCodes,
  oauthAccessTokens,
  oauthRefreshTokens,
  // Platform User Roles
  platformRoleEnum,
  platformUserRoles,
  // Impersonation
  impersonationGrants,
  // Access Control
  accessRequestStatusEnum,
  platformSettings,
  accessAllowlist,
  accessRequests,
  // Change Requests
  changeRequestStatusEnum,
  changeRequests,
  changeRequestsRelations,
  // Review Center
  reviewItemKindEnum,
  reviewItemStatusEnum,
  reviewItemRiskEnum,
  reviewItemSourceEnum,
  reviewItems,
  reviewItemsRelations,
  // IAM
  accountGroupSourceEnum,
  accountGroups,
  accountGroupMembers,
  projectGroupGrants,
  accountGroupsRelations,
  accountGroupMembersRelations,
  iamRoles,
  iamRoleActions,
  iamPolicies,
  iamResourceGrants,
  iamRolesRelations,
  iamRoleActionsRelations,
  // Canonical RBAC (PR2). `permissions` is the action catalog, `roleAssignments`
  // the ONE grant table, `objectPolicies` the per-object-type unscoped default.
  // The canonical NAMES kortix.roles / kortix.role_permissions /
  // kortix.group_members are write-through views over iamRoles /
  // iamRoleActions / accountGroupMembers until the cutover migration swaps
  // which side is physical — so those three keep their existing exports.
  permissions,
  objectPolicies,
  roleAssignments,
  roleAssignmentsRelations,
  // SCIM
  scimTokens,
  // Audit webhooks
  auditWebhooks,
  auditWebhookDeliveries,
  // SAML SSO
  accountSsoProviders,
  accountSsoGroupMappings,
  // Session policy
  accountSessionActivity,
  // Service accounts
  serviceAccounts,
  // Connector (connectors)
  connectorProviderEnum,
  connectorStatusEnum,
  connectorPolicyActionEnum,
  connectorRiskEnum,
  connectorCallStatusEnum,
  connectorCredentialModeEnum,
  connectorConnectionOwnerTypeEnum,
  connectorConnectionStatusEnum,
  projectSessionConnectorBindingSourceEnum,
  connectors,
  connectorConnections,
  projectSessionConnectorBindings,
  connectionCredentials,
  connectionOAuthApplications,
  connectionOAuthSessions,
  connectorActions,
  connectionPolicies,
  connectorPolicies,
  connectorProjectPolicies,
  connectorProjectSettings,
  connectorCalls,
  connectorAttachments,
  sessionToolApprovals,
  connectorsRelations,
  connectorActionsRelations,
  connectorPoliciesRelations,
  connectorProjectPoliciesRelations,
  connectorProjectSettingsRelations,
} from './schema/kortix';
export type { AgentGrant } from './schema/kortix';
export type { AccountBrandingRecord } from './schema/kortix';
export type { SecretEgressPolicy, SecretEgressRule, SecretInjectionSlot } from './schema/kortix';

export type {
  TunnelMachineInfo,
  TunnelFilesystemScope,
  TunnelShellScope,
  TunnelNetworkScope,
  TunnelPermissionScope,
} from './schema/kortix';

// Public tables
export { apiKeys } from './schema/public';

export type {
  Account,
  AccountMember,
  NewAccount,
  NewAccountMember,
  Project,
  NewProject,
  ProjectMember,
  NewProjectMember,
  ProjectSecret,
  NewProjectSecret,
  ChatChannelBinding,
  NewChatChannelBinding,
  ChatThread,
  NewChatThread,
  ProjectSession,
  NewProjectSession,
  ProjectSnapshotBuild,
  NewProjectSnapshotBuild,
  SandboxTemplate as DbSandboxTemplate,
  NewSandboxTemplate as NewDbSandboxTemplate,
  Sandbox,
  NewSandbox,
  SessionSandbox,
  NewSessionSandbox,
  ApiKey,
  CreditAccount,
  NewApiKey,
  SandboxSelect,
  KortixApiKey,
  NewKortixApiKey,
  TunnelConnection,
  NewTunnelConnection,
  TunnelPermission,
  NewTunnelPermission,
  TunnelPermissionRequest,
  NewTunnelPermissionRequest,
  TunnelAuditLog,
  NewTunnelAuditLog,
  GatewayRequestLog,
  NewGatewayRequestLog,
  GatewayApiKey,
  NewGatewayApiKey,
  GatewayBudget,
  NewGatewayBudget,
} from './types';
