// Main exports
export { createDb, type Database } from './client';
export * as schema from './schema';

// Re-export frequently used schemas and types for convenience
export {
  // Schema namespace
  kortixSchema,
  // Enums
  sandboxStatusEnum,
	  projectStatusEnum,
	  projectSessionStatusEnum,
	  sessionLifecycleCommandStatusEnum,
	  projectRoleEnum,
  projectAccessRequestStatusEnum,
  apiKeyStatusEnum,
  apiKeyTypeEnum,
  // Kortix tables — accounts
  accounts,
  accountMembers,
  accountInvitations,
  accountGithubInstallations,
  accountGithubInstallationStates,
  accountRoleEnum,
  accountsRelations,
  accountMembersRelations,
  accountGithubInstallationsRelations,
  auditEvents,
  usageEvents,
  gatewayRequestLogs,
  gatewayApiKeys,
  gatewayBudgets,
  // Kortix tables
  projects,
  projectGitConnections,
  projectGitCredentials,
  projectMembers,
  projectAccessRequests,
  projectSecrets,
  secretShareScopeEnum,
  secretGrantPrincipalEnum,
  projectSecretScopeEnum,
	  projectTriggerRuntime,
	  sessionLifecycleCommands,
	  chatChannelBindings,
  chatInstalls,
  chatPendingAuthMessages,
  chatThreads,
  chatThreadParticipants,
  chatTurnStreams,
  teamsPendingUploads,
  chatEventDedup,
  chatUserIdentities,
  projectSessions,
  projectSessionRuntimeContexts,
  accountModelPreferences,
  projectLlmRoutingPolicies,
  projectSessionGrants,
  projectSessionPublicShares,
  projectSessionVisibilityEnum,
  projectSnapshotBuilds,
  providerTransitions,
  providerTransitionStatusEnum,
  sandboxTemplates,
  sessionSandboxes,
  sessionSandboxStatusEnum,
  providerEvents,
  sandboxes,
  sandboxMembers,
  sandboxMemberScopes,
  scopeEffectEnum,
  sandboxInvites,
  legacySandboxMigrations,
  sunaAccountMigrations,
  kortixApiKeys,
  accountTokens,
  workerLeaderLease,
  // Relations
  projectsRelations,
  projectGitConnectionsRelations,
  projectGitCredentialsRelations,
  projectMembersRelations,
  projectSecretsRelations,
  projectSessionsRelations,
  projectSessionRuntimeContextsRelations,
  sandboxesRelations,
  sandboxMembersRelations,
  sandboxInvitesRelations,
  kortixApiKeysRelations,
  // Billing / Credits (moved from public → kortix schema)
  billingCustomers,
  creditAccounts,
  creditLedger,
  creditUsage,
  accountDeletionRequests,
  creditPurchases,
  // Billing v2 — per-seat + compute metering + per-member YOLO
  sandboxComputeSessions,
  yoloMemberTokens,
  stripeWebhookEventsProcessed,
  // Tunnel
  tunnelStatusEnum,
  tunnelCapabilityEnum,
  tunnelPermissionStatusEnum,
  tunnelPermissionRequestStatusEnum,
  tunnelConnections,
  tunnelPermissions,
  tunnelPermissionRequests,
  tunnelAuditLogs,
  tunnelRpcForwards,
  tunnelDeviceAuthStatusEnum,
  tunnelDeviceAuthRequests,
  tunnelConnectionsRelations,
  tunnelPermissionsRelations,
  tunnelPermissionRequestsRelations,
  tunnelAuditLogsRelations,
  // OAuth2 Provider
  oauthClients,
  oauthAuthorizationCodes,
  oauthAccessTokens,
  oauthRefreshTokens,
  // Platform User Roles
  platformRoleEnum,
  platformUserRoles,
  // Access Control
  accessRequestStatusEnum,
  platformSettings,
  accessAllowlist,
  accessRequests,
  // Change Requests
  changeRequestStatusEnum,
  changeRequests,
  changeRequestsRelations,
  // Review Center
  reviewItemKindEnum,
  reviewItemStatusEnum,
  reviewItemRiskEnum,
  reviewItemSourceEnum,
  reviewItems,
  reviewItemsRelations,
  // IAM
  accountGroupSourceEnum,
  accountGroups,
  accountGroupMembers,
  projectGroupGrants,
  accountGroupsRelations,
  accountGroupMembersRelations,
  iamRoles,
  iamRoleActions,
  iamPolicies,
  iamResourceGrants,
  iamRolesRelations,
  iamRoleActionsRelations,
  // SCIM
  scimTokens,
  // Audit webhooks
  auditWebhooks,
  // SAML SSO
  accountSsoProviders,
  accountSsoGroupMappings,
  // Session policy
  accountSessionActivity,
  // Service accounts
  serviceAccounts,
  // Executor (connectors)
  executorConnectorProviderEnum,
  executorConnectorStatusEnum,
  executorPolicyActionEnum,
  executorRiskEnum,
  executorExecutionStatusEnum,
  executorCredentialModeEnum,
  executorConnectionProfileOwnerTypeEnum,
  executorConnectionProfileStatusEnum,
  projectSessionConnectorBindingSourceEnum,
  executorConnectors,
  executorConnectionProfiles,
  projectSessionConnectorBindings,
  executorConnectorGrants,
  executorCredentials,
  executorConnectorActions,
  executorConnectorPolicies,
  executorProjectPolicies,
  executorProjectSettings,
  executorExecutions,
  sessionToolApprovals,
  executorConnectorsRelations,
  executorConnectorActionsRelations,
  executorConnectorPoliciesRelations,
  executorProjectPoliciesRelations,
  executorProjectSettingsRelations,
} from './schema/kortix';
export type { AgentGrant } from './schema/kortix';

export type {
  TunnelMachineInfo,
  TunnelFilesystemScope,
  TunnelShellScope,
  TunnelNetworkScope,
  TunnelPermissionScope,
} from './schema/kortix';

// Public tables
export { apiKeys } from './schema/public';

export type {
  Account,
  AccountMember,
  NewAccount,
  NewAccountMember,
  Project,
  NewProject,
  ProjectMember,
  NewProjectMember,
  ProjectSecret,
  NewProjectSecret,
  ChatChannelBinding,
  NewChatChannelBinding,
  ChatThread,
  NewChatThread,
  ProjectSession,
  NewProjectSession,
  ProjectSnapshotBuild,
  NewProjectSnapshotBuild,
  SandboxTemplate as DbSandboxTemplate,
  NewSandboxTemplate as NewDbSandboxTemplate,
  Sandbox,
  NewSandbox,
  SessionSandbox,
  NewSessionSandbox,
  ApiKey,
  CreditAccount,
  NewApiKey,
  SandboxSelect,
  KortixApiKey,
  NewKortixApiKey,
  TunnelConnection,
  NewTunnelConnection,
  TunnelPermission,
  NewTunnelPermission,
  TunnelPermissionRequest,
  NewTunnelPermissionRequest,
  TunnelAuditLog,
  NewTunnelAuditLog,
  GatewayRequestLog,
  NewGatewayRequestLog,
  GatewayApiKey,
  NewGatewayApiKey,
  GatewayBudget,
  NewGatewayBudget,
} from './types';
