/* Name mapping for the one-shot phosphor migration. Sources without an entry
   here fall back to the `name + 'Icon'` rule, checked against the package's
   real exports at runtime. */

export const MANUAL_MAP = {
  "lucide-react": {
    "ChevronRight": "CaretRightIcon",
    "ChevronRightIcon": "CaretRightIcon",
    "ChevronDown": "CaretDownIcon",
    "ChevronDownIcon": "CaretDownIcon",
    "ChevronLeft": "CaretLeftIcon",
    "ChevronUp": "CaretUpIcon",
    "ChevronsUpDown": "CaretUpDownIcon",
    "Search": "MagnifyingGlassIcon",
    "Loader2": "CircleNotchIcon",
    "ExternalLink": "ArrowSquareOutIcon",
    "RefreshCw": "ArrowsClockwiseIcon",
    "RefreshCcw": "ArrowsCounterClockwiseIcon",
    "KeyRound": "KeyIcon",
    "AlertTriangle": "WarningIcon",
    "TriangleAlert": "WarningIcon",
    "Trash2": "TrashIcon",
    "Layers": "StackIcon",
    "Layers2": "StackSimpleIcon",
    "Boxes": "CubeIcon",
    "AlertCircle": "WarningCircleIcon",
    "CircleAlert": "WarningCircleIcon",
    "Mail": "EnvelopeIcon",
    "MailCheck": "EnvelopeOpenIcon",
    "Bot": "RobotIcon",
    "MoreHorizontal": "DotsThreeIcon",
    "Ellipsis": "DotsThreeIcon",
    "MoreVertical": "DotsThreeVerticalIcon",
    "Sparkles": "SparkleIcon",
    "RotateCcw": "ArrowCounterClockwiseIcon",
    "RotateCw": "ArrowClockwiseIcon",
    "History": "ClockCounterClockwiseIcon",
    "MessageSquare": "ChatIcon",
    "MessageSquarePlus": "ChatIcon",
    "MessageCircle": "ChatCircleIcon",
    "MessagesSquare": "ChatsIcon",
    "CheckCircle2": "CheckCircleIcon",
    "CircleCheckBig": "CheckCircleIcon",
    "FileDiff": "GitDiffIcon",
    "Zap": "LightningIcon",
    "FileCode2": "FileCodeIcon",
    "Maximize2": "ArrowsOutSimpleIcon",
    "Minimize2": "ArrowsInSimpleIcon",
    "Maximize": "CornersOutIcon",
    "Minimize": "CornersInIcon",
    "ShieldAlert": "ShieldWarningIcon",
    "Webhook": "WebhooksLogoIcon",
    "CalendarClock": "CalendarDotsIcon",
    "ScrollText": "ScrollIcon",
    "FolderGit2": "GitBranchIcon",
    "Code2": "CodeSimpleIcon",
    "Server": "HardDrivesIcon",
    "ServerOff": "CloudSlashIcon",
    "HelpCircle": "QuestionIcon",
    "CircleHelp": "QuestionIcon",
    "Store": "StorefrontIcon",
    "Blocks": "SquaresFourIcon",
    "PanelLeft": "SidebarSimpleIcon",
    "PanelLeftIcon": "SidebarSimpleIcon",
    "PanelLeftClose": "SidebarSimpleIcon",
    "PanelRight": "SidebarSimpleIcon",
    "Github": "GithubLogoIcon",
    "LogOut": "SignOutIcon",
    "LogIn": "SignInIcon",
    "Ban": "ProhibitIcon",
    "Container": "ShippingContainerIcon",
    "Volume2": "SpeakerHighIcon",
    "VolumeX": "SpeakerSlashIcon",
    "FileSpreadsheet": "FileXlsIcon",
    "CircleMinus": "MinusCircleIcon",
    "CirclePlus": "PlusCircleIcon",
    "FileIcon": "FileIcon",
    "FileEdit": "NotePencilIcon",
    "FilePen": "NotePencilIcon",
    "FilePlus2": "FilePlusIcon",
    "FileX2": "FileXIcon",
    "ListTodo": "ListChecksIcon",
    "ArrowUpCircle": "ArrowCircleUpIcon",
    "Building2": "BuildingsIcon",
    "DollarSign": "CurrencyDollarIcon",
    "Save": "FloppyDiskIcon",
    "Type": "TextTIcon",
    "CheckIcon": "CheckIcon",
    "Smartphone": "DeviceMobileIcon",
    "FileWarning": "FileXIcon",
    "ListTree": "TreeStructureIcon",
    "Unplug": "PlugsIcon",
    "EyeOff": "EyeSlashIcon",
    "Settings": "GearSixIcon",
    "Cable": "PlugsConnectedIcon",
    "Workflow": "FlowArrowIcon",
    "Box": "PackageIcon",
    "Filter": "FunnelIcon",
    "UserRound": "UserCircleIcon",
    "UserRoundSearch": "UserFocusIcon",
    "UserSearch": "UserFocusIcon",
    "Send": "PaperPlaneTiltIcon",
    "Link2": "LinkSimpleIcon",
    "Share2": "ShareNetworkIcon",
    "ZoomIn": "MagnifyingGlassPlusIcon",
    "ZoomOut": "MagnifyingGlassMinusIcon",
    "AtSign": "AtIcon",
    "BarChart3": "ChartBarIcon",
    "FlaskConical": "FlaskIcon",
    "Scale": "ScalesIcon",
    "ClipboardCopy": "ClipboardIcon",
    "ClipboardCheck": "ListChecksIcon",
    "ClipboardList": "ClipboardTextIcon",
    "Music": "MusicNotesIcon",
    "Wand2": "MagicWandIcon",
    "SquareTerminal": "TerminalWindowIcon",
    "TerminalSquare": "TerminalWindowIcon",
    "FileTerminal": "TerminalWindowIcon",
    "Columns2": "ColumnsIcon",
    "FileSymlink": "FileArrowUpIcon",
    "FileType": "FileTextIcon",
    "Reply": "ArrowBendUpLeftIcon",
    "GitCompareArrows": "GitDiffIcon",
    "SquareKanban": "KanbanIcon",
    "FolderKanban": "KanbanIcon",
    "LayoutDashboard": "SquaresFourIcon",
    "ArrowRightLeft": "ArrowsLeftRightIcon",
    "ArrowLeftRight": "ArrowsLeftRightIcon",
    "ShieldOff": "ShieldSlashIcon",
    "CalendarIcon": "CalendarIcon",
    "Grid2x2": "GridFourIcon",
    "WifiOff": "WifiSlashIcon",
    "Menu": "ListIcon",
    "MoonStar": "MoonStarsIcon",
    "LockKeyhole": "LockIcon",
    "CircleIcon": "CircleIcon",
    "AlarmClock": "AlarmIcon",
    "CircleDollarSign": "CurrencyCircleDollarIcon",
    "FileLock2": "FileLockIcon",
    "FileSignature": "SignatureIcon",
    "LineChart": "ChartLineIcon",
    "Radar": "BroadcastIcon",
    "Route": "PathIcon",
    "TrendingDown": "TrendDownIcon",
    "TrendingUp": "TrendUpIcon",
    "ImageOff": "ImageBrokenIcon",
    "Edit": "PencilSimpleIcon",
    "Edit3": "PencilSimpleIcon",
    "Table2": "TableIcon",
    "FileQuestion": "FileMagnifyingGlassIcon",
    "Undo2": "ArrowUUpLeftIcon",
    "Braces": "BracketsCurlyIcon",
    "LifeBuoy": "LifebuoyIcon",
    "FolderTree": "TreeViewIcon",
    "PenTool": "PenNibIcon",
    "Puzzle": "PuzzlePieceIcon",
    "PackageSearch": "PackageIcon",
    "Rows2": "RowsIcon",
    "Rows3": "RowsIcon",
    "LayoutGrid": "SquaresFourIcon",
    "FolderCog": "FolderIcon",
    "FileCog": "GearSixIcon",
    "ArrowUpDown": "ArrowsDownUpIcon",
    "FolderRoot": "FolderIcon",
    "FileJson": "FileCodeIcon",
    "FileKey": "FileLockIcon",
    "FileMusic": "FileAudioIcon",
    "FileBadge": "CertificateIcon",
    "FileBox": "FileArchiveIcon",
    "FileChartLine": "ChartLineIcon",
    "FileDown": "FileArrowDownIcon",
    "Glasses": "EyeglassesIcon",
    "Mic": "MicrophoneIcon",
    "CornerDownLeft": "ArrowElbowDownLeftIcon",
    "CornerDownRight": "ArrowElbowDownRightIcon",
    "AudioLines": "WaveformIcon",
    "Inbox": "TrayIcon",
    "ShieldQuestion": "SealQuestionIcon",
    "SquareSlash": "ProhibitIcon",
    "CircleDot": "RadioButtonIcon",
    "CircleDotDashed": "CircleDashedIcon",
    "Wallpaper": "ImagesSquareIcon",
    "Bold": "TextBIcon",
    "AlertOctagon": "WarningOctagonIcon",
    "StarOff": "StarIcon"
  },
  "react-icons": {
    "HiArrowRight": "ArrowRightIcon",
    "HiMiniSparkles": "SparkleIcon",
    "FaUsers": "UsersIcon",
    "MdShield": "ShieldIcon",
    "RiCpuLine": "CpuIcon",
    "GrRefresh": "ArrowsClockwiseIcon",
    "TbExternalLink": "ArrowSquareOutIcon",
    "PiChatCircleDotsFill": "ChatCircleDotsIcon",
    "RiFolder3Fill": "FolderIcon",
    "RiRobot3Fill": "RobotIcon",
    "AiOutlineCheck": "CheckIcon",
    "FaWindows": "WindowsLogoIcon",
    "RiMicAiFill": "MicrophoneIcon",
    "PiCheckCircleFill": "CheckCircleIcon",
    "GoHomeFill": "HouseIcon",
    "PiClockCountdownFill": "ClockCountdownIcon",
    "HiOutlineSlash": "LineVerticalIcon",
    "GoCheckCircleFill": "CheckCircleIcon",
    "HiOutlineExclamationCircle": "WarningCircleIcon",
    "HiOutlineXCircle": "XCircleIcon",
    "CgClose": "XIcon",
    "PiSmileyMeltingFill": "SmileyMeltingIcon",
    "LuSettings": "GearSixIcon",
    "LuUsersRound": "UsersThreeIcon",
    "HiOutlineViewGrid": "SquaresFourIcon",
    "HiDotsHorizontal": "DotsThreeIcon"
  },
  "@mynaui/icons-react": {
    "CheckCircleSolid": "CheckCircleIcon",
    "TrashSolid": "TrashIcon",
    "DangerTriangleSolid": "WarningIcon",
    "Search": "MagnifyingGlassIcon",
    "SparklesSolid": "SparkleIcon",
    "UsersSolid": "UsersIcon",
    "CogOne": "GearSixIcon",
    "CogOneSolid": "GearSixIcon",
    "Config": "GearSixIcon",
    "ChevronRight": "CaretRightIcon",
    "ChevronDown": "CaretDownIcon",
    "ShieldCheckSolid": "ShieldCheckIcon",
    "CreditCardSolid": "CreditCardIcon",
    "HomeSolid": "HouseIcon",
    "QuestionCircleSolid": "QuestionIcon",
    "ChevronsUpDown": "CaretUpDownIcon",
    "ChevronsUpDownSolid": "CaretUpDownIcon",
    "ChatMessages": "ChatsIcon",
    "XCircleSolid": "XCircleIcon",
    "TelephoneSolid": "PhoneIcon",
    "AlarmClock": "AlarmIcon",
    "AlarmClockSolid": "AlarmIcon",
    "PauseSolid": "PauseIcon",
    "PlaySolid": "PlayIcon",
    "ShieldSolid": "ShieldIcon",
    "BellSolid": "BellIcon",
    "EyeOffSolid": "EyeSlashIcon",
    "InfoCircleSolid": "InfoIcon",
    "ListSolid": "ListIcon",
    "InboxSolid": "TrayIcon",
    "Send": "PaperPlaneTiltIcon",
    "BanSolid": "ProhibitIcon",
    "Sparkles": "SparkleIcon",
    "StarSolid": "StarIcon",
    "Refresh": "ArrowsClockwiseIcon",
    "ExternalLinkSolid": "ArrowSquareOutIcon",
    "UsersGroupSolid": "UsersThreeIcon",
    "LockSolid": "LockIcon"
  },
  "@icons-pack/react-simple-icons": {
    "SiApple": "AppleLogoIcon",
    "SiLinux": "LinuxLogoIcon"
  }
};

/* Type-only names, per source library: alias back so bodies stay untouched
   (e.g. `import { type Icon as LucideIcon }`). */
export const TYPE_MAP = {
  'lucide-react': { LucideIcon: 'Icon', LucideProps: 'IconProps' },
  'react-icons': { IconType: 'Icon' },
  '@mynaui/icons-react': { Icon: 'Icon' },
};

/* Source icons that are filled on purpose (status tiles, success checks,
   destructive trash). Their direct JSX usages get an explicit weight="fill"
   so they keep today's hierarchy regardless of the global weight toggle. */
export const FILL_INTENT_SOURCES = new Set([
  ...Object.keys(MANUAL_MAP['@mynaui/icons-react']).filter((n) =>
    n.endsWith('Solid'),
  ),
  ...Object.keys(MANUAL_MAP['react-icons']).filter((n) => /Fill$/.test(n)),
  'HiMiniSparkles',
  'FaUsers',
  'MdShield',
  'FaWindows',
  'SiApple',
  'SiLinux',
]);
