/**
 * Mock Review Center data — prototype only. Shapes mirror the real systems the
 * production read model would adapt from (change requests, connector approvals,
 * agent-submitted outputs/decisions/batches). Timestamps are relative to load so
 * the inbox always reads fresh.
 */

import type { ReviewItem } from './types';

const now = Date.now();
const ago = (mins: number) => new Date(now - mins * 60_000).toISOString();

const batchChildren = [
  'Add alt text to 6 marketing images',
  'Fix the broken footer link on /pricing',
  'Normalize button casing across the docs',
  'Compress 12 oversized hero images',
  'Add missing meta descriptions to 4 blog posts',
  'Update the 2024 copyright year in the footer',
  'Redirect 3 dead /old-* URLs',
  'Add aria-labels to the nav icons',
  'Fix the mobile padding on the FAQ section',
  'Replace 2 placeholder testimonials',
  'Wire the newsletter form to the real list',
  'Add a loading state to the contact form',
  'Tighten the changelog spacing',
].map((title, i) => ({
  id: `bt-${i}`,
  title,
  status: i >= 11 ? ('needs_review' as const) : ('done' as const),
}));

export const MOCK_ITEMS: ReviewItem[] = [
  // ── Needs you ─────────────────────────────────────────────────────────────
  {
    id: 'rv-change-1',
    kind: 'change',
    title: 'Refresh the pricing page and checkout copy',
    summary: '5 files touched · preview ready · tests passed',
    risk: 'medium',
    status: 'needs_you',
    source: 'web',
    project: 'Acme Marketing Site',
    agent: 'Suna · session “pricing-refresh”',
    actor: { name: 'Suna', initials: 'SU' },
    createdAt: ago(7),
    primaryAction: 'Ship it',
    secondaryAction: 'Ask for changes',
    detail: {
      whatChanged: [
        'Rewrote the pricing headline and the three plan cards',
        'Updated the checkout confirmation message',
        'Changed one config file (feature flags)',
      ],
      impact: 'Medium change · 5 files · touches a config file',
      verification: [
        { label: 'Preview ready', tone: 'info' },
        { label: 'Tests passed', tone: 'success' },
      ],
      previewUrl: 'https://preview.kortix.dev/pricing-refresh',
      advanced: {
        headRef: 'session/8f1c2a90-pricing-refresh',
        baseRef: 'main',
        headSha: 'a1b2c3d4e5f6',
        baseSha: '0099fedcba98',
        additions: 142,
        deletions: 38,
        mergeMode: 'fast-forward',
        files: [
          { path: 'app/pricing/page.tsx', status: 'modified', additions: 64, deletions: 18 },
          {
            path: 'app/checkout/confirmation.tsx',
            status: 'modified',
            additions: 31,
            deletions: 9,
          },
          { path: 'components/plan-card.tsx', status: 'modified', additions: 28, deletions: 7 },
          { path: 'content/pricing.mdx', status: 'modified', additions: 14, deletions: 4 },
          { path: 'config/flags.ts', status: 'modified', additions: 5, deletions: 0 },
        ],
      },
    },
  },
  {
    id: 'rv-approval-1',
    kind: 'approval',
    title: 'Send the Q3 launch announcement',
    summary: '4 actions · 2 are safe to approve together, 2 need a closer look',
    risk: 'high',
    status: 'needs_you',
    source: 'slack',
    project: 'Acme Growth',
    agent: 'Growth agent · thread #launches',
    actor: { name: 'Growth agent', initials: 'GA' },
    createdAt: ago(12),
    primaryAction: 'Review actions',
    detail: {
      actions: [
        {
          id: 'ap-1',
          title: 'Read the campaign recipient list',
          connector: 'Google Sheets',
          action: 'sheets.values.get',
          consequence: 'Reads 214 rows from “Q3 Launch List”. No changes made.',
          risk: 'low',
          icon: 'data',
          policySource: 'Project policy · read actions run automatically',
          argsPreview: [
            { key: 'spreadsheet', value: 'Q3 Launch List' },
            { key: 'range', value: 'A2:C215' },
          ],
        },
        {
          id: 'ap-2',
          title: 'Upload the launch banner image',
          connector: 'Cloudinary',
          action: 'assets.upload',
          consequence: 'Uploads 1 image to the shared media library.',
          risk: 'low',
          icon: 'generic',
          policySource: 'Project policy · low-risk writes',
          argsPreview: [{ key: 'file', value: 'q3-launch-banner.png' }],
        },
        {
          id: 'ap-3',
          title: 'Post to the #announcements channel',
          connector: 'Slack',
          action: 'chat.postMessage',
          consequence: 'Posts a message visible to ~600 people in #announcements.',
          risk: 'medium',
          icon: 'command',
          policySource: 'Project policy · write actions need approval',
          argsPreview: [
            { key: 'channel', value: '#announcements' },
            { key: 'text', value: '🚀 Q3 is live — here’s what shipped…' },
          ],
        },
        {
          id: 'ap-4',
          title: 'Send the launch email to 214 recipients',
          connector: 'Gmail',
          action: 'messages.send',
          consequence: 'Sends a real email to 214 external recipients. Cannot be undone.',
          risk: 'high',
          icon: 'email',
          policySource: 'Project policy · bulk send needs approval',
          argsPreview: [
            { key: 'to', value: '214 recipients' },
            { key: 'subject', value: 'Acme Q3 is here' },
          ],
        },
      ],
    },
  },
  {
    id: 'rv-output-1',
    kind: 'output',
    title: 'Review the new launch landing page before I publish',
    summary: 'Landing page · built from the Q3 brief · not live yet',
    risk: 'low',
    status: 'needs_you',
    source: 'agent',
    project: 'Acme Growth',
    agent: 'Growth agent · session “q3-landing”',
    actor: { name: 'Growth agent', initials: 'GA' },
    createdAt: ago(26),
    primaryAction: 'Approve & publish',
    secondaryAction: 'Request changes',
    detail: {
      artifactKind: 'page',
      artifactLabel: 'Landing page',
      previewUrl: 'https://preview.kortix.dev/q3-landing',
      note: 'I built the Q3 launch landing page from your brief. Want to look before it goes live? I can publish it the moment you approve.',
      preview:
        'Hero: “Ship faster with Acme.” · 3 feature blocks · social proof row · pricing CTA · FAQ · footer.',
      files: [
        { path: 'app/q3-landing/page.tsx', note: 'the page' },
        { path: 'app/q3-landing/sections/*', note: '6 sections' },
      ],
    },
  },
  {
    id: 'rv-decision-1',
    kind: 'decision',
    title: 'Which database should the new notifications service use?',
    summary: 'I can go either way — your call decides the schema work',
    risk: 'none',
    status: 'needs_you',
    source: 'agent',
    project: 'Platform',
    agent: 'Backend agent · session “notify-svc”',
    actor: { name: 'Backend agent', initials: 'BA' },
    createdAt: ago(41),
    primaryAction: 'Answer',
    detail: {
      question: 'Pick the datastore for the notifications service.',
      context:
        'Notifications are write-heavy and short-lived. All three work; the choice mostly affects ops and cost.',
      options: [
        {
          id: 'opt-pg',
          label: 'Postgres',
          description: 'Reuses our existing DB and backups. Simplest to operate.',
          recommended: true,
        },
        {
          id: 'opt-dynamo',
          label: 'DynamoDB',
          description: 'Scales effortlessly but adds a new vendor and access pattern.',
        },
        {
          id: 'opt-sqlite',
          label: 'SQLite (per-region)',
          description: 'Cheapest, but harder to query across regions.',
        },
      ],
    },
  },
  {
    id: 'rv-batch-1',
    kind: 'batch',
    title: '13 site-polish tasks finished',
    summary: '11 done and verified · 2 want a quick look',
    risk: 'low',
    status: 'needs_you',
    source: 'web',
    project: 'Acme Marketing Site',
    agent: 'Suna · session “site-polish”',
    actor: { name: 'Suna', initials: 'SU' },
    createdAt: ago(58),
    primaryAction: 'Approve all',
    secondaryAction: 'Open list',
    detail: {
      note: 'I cleared the site-polish backlog. 11 are done and verified; 2 changed copy you might want to read first.',
      children: batchChildren,
    },
  },

  {
    id: 'rv-change-conflict',
    kind: 'change',
    title: 'Add a testimonials section to the homepage',
    summary: 'Overlaps with recent homepage edits — resolve before shipping',
    risk: 'medium',
    status: 'needs_you',
    source: 'agent',
    project: 'Acme Marketing Site',
    agent: 'Suna · session “testimonials”',
    actor: { name: 'Suna', initials: 'SU' },
    createdAt: ago(18),
    primaryAction: 'Ship it',
    secondaryAction: 'Ask for changes',
    detail: {
      whatChanged: [
        'Added a testimonials section with 3 customer quotes',
        'Wired it into the homepage below the hero',
      ],
      impact: 'Medium change · 3 files · overlaps recent work',
      verification: [{ label: 'Not tested yet', tone: 'neutral' }],
      conflicts: ['the homepage hero', 'the homepage layout', 'shared styles'],
      advanced: {
        headRef: 'session/testimonials',
        baseRef: 'main',
        headSha: 'bb44cc55dd66',
        baseSha: '0099fedcba98',
        additions: 96,
        deletions: 12,
        mergeMode: '3-way',
        files: [
          { path: 'app/(marketing)/page.tsx', status: 'modified', additions: 40, deletions: 10 },
          { path: 'components/testimonials.tsx', status: 'added', additions: 52, deletions: 0 },
          { path: 'app/globals.css', status: 'modified', additions: 4, deletions: 2 },
        ],
      },
    },
  },

  // ── Waiting ───────────────────────────────────────────────────────────────
  {
    id: 'rv-change-2',
    kind: 'change',
    title: 'Migrate the blog to MDX',
    summary: 'You approved this — the agent is running the migration now',
    risk: 'medium',
    status: 'waiting',
    source: 'web',
    project: 'Acme Marketing Site',
    agent: 'Suna · session “blog-mdx”',
    actor: { name: 'Suna', initials: 'SU' },
    createdAt: ago(95),
    primaryAction: 'View progress',
    detail: {
      whatChanged: ['Converting 38 blog posts to MDX', 'Rewiring the blog index and RSS feed'],
      impact: 'Large change · 41 files',
      verification: [{ label: 'Migration running', tone: 'neutral' }],
      advanced: {
        headRef: 'session/blog-mdx',
        baseRef: 'main',
        headSha: 'cc11dd22ee33',
        baseSha: '0099fedcba98',
        additions: 980,
        deletions: 410,
        mergeMode: '3-way',
        files: [{ path: 'content/blog/*.mdx', status: 'added', additions: 980, deletions: 0 }],
      },
    },
  },
  {
    id: 'rv-approval-2',
    kind: 'approval',
    title: 'Deploy the API to staging',
    summary: 'You approved this 4 minutes ago — deploy in progress',
    risk: 'medium',
    status: 'waiting',
    source: 'slack',
    project: 'Platform',
    agent: 'Release agent · thread #deploys',
    actor: { name: 'Release agent', initials: 'RA' },
    createdAt: ago(4),
    primaryAction: 'View deploy',
    detail: {
      actions: [
        {
          id: 'ap-d1',
          title: 'Deploy api@a1b2c3 to staging',
          connector: 'Argo',
          action: 'deploy.staging',
          consequence: 'Rolls the staging API to a new image. Reversible.',
          risk: 'medium',
          icon: 'command',
          policySource: 'Project policy · deploys need approval',
          argsPreview: [{ key: 'env', value: 'staging' }],
          decided: 'approved',
        },
      ],
    },
  },

  // ── Done ──────────────────────────────────────────────────────────────────
  {
    id: 'rv-output-2',
    kind: 'output',
    title: 'Q2 performance report',
    summary: 'You approved this yesterday',
    risk: 'none',
    status: 'approved',
    source: 'agent',
    project: 'Acme Growth',
    agent: 'Analytics agent',
    actor: { name: 'Analytics agent', initials: 'AA' },
    createdAt: ago(1500),
    primaryAction: 'View',
    detail: {
      artifactKind: 'document',
      artifactLabel: 'Report',
      note: 'Q2 performance report — approved and shared with the team.',
      preview: '12-page PDF · revenue, activation, retention, and a Q3 recommendation.',
    },
  },
  {
    id: 'rv-decision-2',
    kind: 'decision',
    title: 'Brand accent color for the new dashboard',
    summary: 'You chose “Kortix blue”',
    risk: 'none',
    status: 'done',
    source: 'web',
    project: 'Platform',
    agent: 'Design agent',
    actor: { name: 'Design agent', initials: 'DA' },
    createdAt: ago(2880),
    primaryAction: 'View',
    detail: {
      question: 'Pick the dashboard accent color.',
      options: [
        { id: 'c1', label: 'Kortix blue', recommended: true },
        { id: 'c2', label: 'Emerald' },
        { id: 'c3', label: 'Violet' },
      ],
    },
  },
  {
    id: 'rv-change-3',
    kind: 'change',
    title: 'Fix the signup form validation',
    summary: 'Shipped to main',
    risk: 'low',
    status: 'done',
    source: 'web',
    project: 'Platform',
    agent: 'Suna · session “signup-fix”',
    actor: { name: 'Suna', initials: 'SU' },
    createdAt: ago(4320),
    primaryAction: 'View',
    detail: {
      whatChanged: ['Fixed email validation on the signup form', 'Added a friendly error message'],
      impact: 'Small change · 2 files',
      verification: [{ label: 'Tests passed', tone: 'success' }],
      advanced: {
        headRef: 'session/signup-fix',
        baseRef: 'main',
        headSha: '77aa88bb99cc',
        baseSha: '0099fedcba98',
        additions: 24,
        deletions: 6,
        mergeMode: 'fast-forward',
        files: [
          { path: 'app/auth/signup-form.tsx', status: 'modified', additions: 24, deletions: 6 },
        ],
      },
    },
  },
];
