/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Integration } from "./Integration";
import { IntegrationCountArgs } from "./IntegrationCountArgs";
import { IntegrationFindManyArgs } from "./IntegrationFindManyArgs";
import { IntegrationFindUniqueArgs } from "./IntegrationFindUniqueArgs";
import { DeleteIntegrationArgs } from "./DeleteIntegrationArgs";
import { IntegrationService } from "../integration.service";
@graphql.Resolver(() => Integration)
export class IntegrationResolverBase {
  constructor(protected readonly service: IntegrationService) {}

  async _integrationsMeta(
    @graphql.Args() args: IntegrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Integration])
  async integrations(
    @graphql.Args() args: IntegrationFindManyArgs
  ): Promise<Integration[]> {
    return this.service.integrations(args);
  }

  @graphql.Query(() => Integration, { nullable: true })
  async integration(
    @graphql.Args() args: IntegrationFindUniqueArgs
  ): Promise<Integration | null> {
    const result = await this.service.integration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Integration)
  async deleteIntegration(
    @graphql.Args() args: DeleteIntegrationArgs
  ): Promise<Integration | null> {
    try {
      return await this.service.deleteIntegration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
