/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { IntegrationService } from "../integration.service";
import { IntegrationCreateInput } from "./IntegrationCreateInput";
import { Integration } from "./Integration";
import { IntegrationFindManyArgs } from "./IntegrationFindManyArgs";
import { IntegrationWhereUniqueInput } from "./IntegrationWhereUniqueInput";
import { IntegrationUpdateInput } from "./IntegrationUpdateInput";

export class IntegrationControllerBase {
  constructor(protected readonly service: IntegrationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Integration })
  async createIntegration(
    @common.Body() data: IntegrationCreateInput
  ): Promise<Integration> {
    return await this.service.createIntegration({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Integration] })
  @ApiNestedQuery(IntegrationFindManyArgs)
  async integrations(@common.Req() request: Request): Promise<Integration[]> {
    const args = plainToClass(IntegrationFindManyArgs, request.query);
    return this.service.integrations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Integration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async integration(
    @common.Param() params: IntegrationWhereUniqueInput
  ): Promise<Integration | null> {
    const result = await this.service.integration({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Integration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateIntegration(
    @common.Param() params: IntegrationWhereUniqueInput,
    @common.Body() data: IntegrationUpdateInput
  ): Promise<Integration | null> {
    try {
      return await this.service.updateIntegration({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Integration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteIntegration(
    @common.Param() params: IntegrationWhereUniqueInput
  ): Promise<Integration | null> {
    try {
      return await this.service.deleteIntegration({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
