'use client';

/**
 * name -> Phosphor component, for the 202 glyphs in the shared catalogue.
 *
 * The imports are EXPLICIT and one per glyph. `import * as Phosphor` would
 * resolve names dynamically and defeat tree-shaking, pulling all 1512 icons
 * (~5.3 MB of path data) into the bundle instead of the 202 we use (~704 KB
 * raw, well under budget gzipped).
 *
 * The catalogue in @kortix/shared is the source of truth for WHICH names exist;
 * this file is the source of truth for what each one DRAWS. glyph-registry.test
 * asserts the two agree in both directions, so a name added to one and not the
 * other fails CI rather than shipping a blank tile.
 */
import {
  AirplaneIcon,
  AlienIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowUUpLeftIcon,
  ArrowUpIcon,
  ArrowsClockwiseIcon,
  ArrowsInIcon,
  ArrowsLeftRightIcon,
  ArrowsOutIcon,
  AsteriskIcon,
  AtIcon,
  BabyIcon,
  BandaidsIcon,
  BankIcon,
  BarbellIcon,
  BaseballIcon,
  BasketballIcon,
  BeerSteinIcon,
  BellIcon,
  BicycleIcon,
  BirdIcon,
  BoatIcon,
  BoneIcon,
  BookIcon,
  BookmarkIcon,
  BreadIcon,
  BriefcaseIcon,
  BugIcon,
  BusIcon,
  ButterflyIcon,
  CactusIcon,
  CakeIcon,
  CarIcon,
  CarrotIcon,
  CatIcon,
  ChartBarIcon,
  ChartLineIcon,
  ChartPieIcon,
  CheckIcon,
  CircleIcon,
  ClipboardIcon,
  CloudIcon,
  CloudLightningIcon,
  CloudRainIcon,
  CloudSnowIcon,
  ClubIcon,
  CodeIcon,
  CoffeeIcon,
  CoinsIcon,
  CookieIcon,
  CopyIcon,
  CowIcon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DatabaseIcon,
  DeviceMobileIcon,
  DiamondIcon,
  DiscIcon,
  DogIcon,
  DropIcon,
  EggIcon,
  EqualizerIcon,
  EraserIcon,
  EyeIcon,
  FeatherIcon,
  FileIcon,
  FileTextIcon,
  FilesIcon,
  FireIcon,
  FirstAidIcon,
  FishIcon,
  FlagIcon,
  FlowerIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FootballIcon,
  GhostIcon,
  GiftIcon,
  GitBranchIcon,
  GolfIcon,
  GuitarIcon,
  HamburgerIcon,
  HammerIcon,
  HandIcon,
  HandshakeIcon,
  HashIcon,
  HeadphonesIcon,
  HeartIcon,
  HeartbeatIcon,
  HexagonIcon,
  HorseIcon,
  IceCreamIcon,
  type Icon,
  InfoIcon,
  JeepIcon,
  KeyIcon,
  KeyboardIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  LinkSimpleIcon,
  LockIcon,
  MartiniIcon,
  MedalIcon,
  MetronomeIcon,
  MicrophoneIcon,
  MinusIcon,
  MonitorIcon,
  MoonIcon,
  MotorcycleIcon,
  MountainsIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  NewspaperIcon,
  NoteIcon,
  NotebookIcon,
  NumberCircleEightIcon,
  NumberCircleFiveIcon,
  NumberCircleFourIcon,
  NumberCircleNineIcon,
  NumberCircleOneIcon,
  NumberCircleSevenIcon,
  NumberCircleSixIcon,
  NumberCircleThreeIcon,
  NumberCircleTwoIcon,
  NumberCircleZeroIcon,
  PackageIcon,
  PaperclipIcon,
  PawPrintIcon,
  PencilIcon,
  PercentIcon,
  PersonSimpleRunIcon,
  PersonSimpleSwimIcon,
  PiggyBankIcon,
  PillIcon,
  PingPongIcon,
  PizzaIcon,
  PlanetIcon,
  PlaylistIcon,
  PlusIcon,
  PolygonIcon,
  QuestionIcon,
  RabbitIcon,
  RacquetIcon,
  RadioIcon,
  RainbowIcon,
  ReceiptIcon,
  RobotIcon,
  RocketIcon,
  ScissorsIcon,
  ScooterIcon,
  ShareNetworkIcon,
  ShoppingCartIcon,
  ShrimpIcon,
  SmileyIcon,
  SmileyMehIcon,
  SmileySadIcon,
  SnowflakeIcon,
  SoccerBallIcon,
  SpadeIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SquareIcon,
  StarIcon,
  StethoscopeIcon,
  SunIcon,
  SunglassesIcon,
  SyringeIcon,
  TagIcon,
  TargetIcon,
  TaxiIcon,
  TennisBallIcon,
  TerminalIcon,
  ThermometerIcon,
  ThumbsUpIcon,
  TrainIcon,
  TrashIcon,
  TreeIcon,
  TrendDownIcon,
  TrendUpIcon,
  TriangleIcon,
  TrophyIcon,
  TruckIcon,
  UmbrellaIcon,
  UserIcon,
  UsersIcon,
  VanIcon,
  VolleyballIcon,
  WalletIcon,
  WarningIcon,
  WaveformIcon,
  WindIcon,
  WineIcon,
  WrenchIcon,
  XIcon,
} from '@phosphor-icons/react';

export const GLYPH_COMPONENTS: Record<string, Icon> = {
  // Objects
  Trash: TrashIcon,
  ShoppingCart: ShoppingCartIcon,
  Package: PackageIcon,
  Briefcase: BriefcaseIcon,
  Gift: GiftIcon,
  Lightbulb: LightbulbIcon,
  Wrench: WrenchIcon,
  Hammer: HammerIcon,
  Key: KeyIcon,
  Lock: LockIcon,
  Umbrella: UmbrellaIcon,
  Trophy: TrophyIcon,
  // Shapes
  Circle: CircleIcon,
  Square: SquareIcon,
  Triangle: TriangleIcon,
  Diamond: DiamondIcon,
  Hexagon: HexagonIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  Lightning: LightningIcon,
  Spade: SpadeIcon,
  Club: ClubIcon,
  Cube: CubeIcon,
  Polygon: PolygonIcon,
  // Files
  File: FileIcon,
  FileText: FileTextIcon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  Note: NoteIcon,
  Book: BookIcon,
  Newspaper: NewspaperIcon,
  Paperclip: PaperclipIcon,
  Archive: ArchiveIcon,
  Notebook: NotebookIcon,
  Files: FilesIcon,
  FolderPlus: FolderPlusIcon,
  // Actions
  Plus: PlusIcon,
  Minus: MinusIcon,
  Copy: CopyIcon,
  Check: CheckIcon,
  X: XIcon,
  Pencil: PencilIcon,
  Bookmark: BookmarkIcon,
  Eraser: EraserIcon,
  Scissors: ScissorsIcon,
  LinkSimple: LinkSimpleIcon,
  ShareNetwork: ShareNetworkIcon,
  Clipboard: ClipboardIcon,
  // Arrows
  ArrowUp: ArrowUpIcon,
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowsClockwise: ArrowsClockwiseIcon,
  ArrowSquareOut: ArrowSquareOutIcon,
  TrendUp: TrendUpIcon,
  TrendDown: TrendDownIcon,
  ArrowsLeftRight: ArrowsLeftRightIcon,
  ArrowUUpLeft: ArrowUUpLeftIcon,
  ArrowsOut: ArrowsOutIcon,
  ArrowsIn: ArrowsInIcon,
  // Tech
  Code: CodeIcon,
  Terminal: TerminalIcon,
  Database: DatabaseIcon,
  Cloud: CloudIcon,
  Cpu: CpuIcon,
  Bug: BugIcon,
  GitBranch: GitBranchIcon,
  Rocket: RocketIcon,
  Monitor: MonitorIcon,
  DeviceMobile: DeviceMobileIcon,
  Keyboard: KeyboardIcon,
  Robot: RobotIcon,
  // Nature
  Leaf: LeafIcon,
  Tree: TreeIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Drop: DropIcon,
  Fire: FireIcon,
  Mountains: MountainsIcon,
  Planet: PlanetIcon,
  Flower: FlowerIcon,
  Cactus: CactusIcon,
  Snowflake: SnowflakeIcon,
  Rainbow: RainbowIcon,
  // Symbols
  Hash: HashIcon,
  At: AtIcon,
  Percent: PercentIcon,
  Asterisk: AsteriskIcon,
  Question: QuestionIcon,
  Warning: WarningIcon,
  Info: InfoIcon,
  Bell: BellIcon,
  Crown: CrownIcon,
  Flag: FlagIcon,
  Medal: MedalIcon,
  Sparkle: SparkleIcon,
  // Food
  Carrot: CarrotIcon,
  Pizza: PizzaIcon,
  Hamburger: HamburgerIcon,
  IceCream: IceCreamIcon,
  Coffee: CoffeeIcon,
  BeerStein: BeerSteinIcon,
  Cookie: CookieIcon,
  Cake: CakeIcon,
  Egg: EggIcon,
  Bread: BreadIcon,
  Wine: WineIcon,
  Martini: MartiniIcon,
  // Animals
  Dog: DogIcon,
  Cat: CatIcon,
  Bird: BirdIcon,
  Butterfly: ButterflyIcon,
  Rabbit: RabbitIcon,
  Horse: HorseIcon,
  Cow: CowIcon,
  PawPrint: PawPrintIcon,
  Fish: FishIcon,
  Shrimp: ShrimpIcon,
  Feather: FeatherIcon,
  Bone: BoneIcon,
  // Transport
  Car: CarIcon,
  Bus: BusIcon,
  Truck: TruckIcon,
  Train: TrainIcon,
  Airplane: AirplaneIcon,
  Bicycle: BicycleIcon,
  Motorcycle: MotorcycleIcon,
  Boat: BoatIcon,
  Scooter: ScooterIcon,
  Taxi: TaxiIcon,
  Van: VanIcon,
  Jeep: JeepIcon,
  // People
  User: UserIcon,
  Users: UsersIcon,
  Smiley: SmileyIcon,
  SmileyMeh: SmileyMehIcon,
  SmileySad: SmileySadIcon,
  Ghost: GhostIcon,
  Alien: AlienIcon,
  Baby: BabyIcon,
  PersonSimpleRun: PersonSimpleRunIcon,
  Hand: HandIcon,
  ThumbsUp: ThumbsUpIcon,
  Eye: EyeIcon,
  // Music
  MusicNote: MusicNoteIcon,
  MusicNotes: MusicNotesIcon,
  Guitar: GuitarIcon,
  Microphone: MicrophoneIcon,
  SpeakerHigh: SpeakerHighIcon,
  Radio: RadioIcon,
  Playlist: PlaylistIcon,
  Metronome: MetronomeIcon,
  Waveform: WaveformIcon,
  Disc: DiscIcon,
  Headphones: HeadphonesIcon,
  Equalizer: EqualizerIcon,
  // Sport
  Basketball: BasketballIcon,
  Football: FootballIcon,
  SoccerBall: SoccerBallIcon,
  Baseball: BaseballIcon,
  TennisBall: TennisBallIcon,
  Barbell: BarbellIcon,
  Target: TargetIcon,
  Golf: GolfIcon,
  Volleyball: VolleyballIcon,
  PingPong: PingPongIcon,
  Racquet: RacquetIcon,
  PersonSimpleSwim: PersonSimpleSwimIcon,
  // Money
  CurrencyDollar: CurrencyDollarIcon,
  Wallet: WalletIcon,
  CreditCard: CreditCardIcon,
  PiggyBank: PiggyBankIcon,
  Coins: CoinsIcon,
  Receipt: ReceiptIcon,
  Bank: BankIcon,
  ChartLine: ChartLineIcon,
  Tag: TagIcon,
  ChartBar: ChartBarIcon,
  ChartPie: ChartPieIcon,
  Handshake: HandshakeIcon,
  // Care
  CloudRain: CloudRainIcon,
  CloudSnow: CloudSnowIcon,
  CloudLightning: CloudLightningIcon,
  Wind: WindIcon,
  Thermometer: ThermometerIcon,
  Sunglasses: SunglassesIcon,
  Heartbeat: HeartbeatIcon,
  Pill: PillIcon,
  FirstAid: FirstAidIcon,
  Syringe: SyringeIcon,
  Bandaids: BandaidsIcon,
  Stethoscope: StethoscopeIcon,
  // Numbers
  NumberCircleZero: NumberCircleZeroIcon,
  NumberCircleOne: NumberCircleOneIcon,
  NumberCircleTwo: NumberCircleTwoIcon,
  NumberCircleThree: NumberCircleThreeIcon,
  NumberCircleFour: NumberCircleFourIcon,
  NumberCircleFive: NumberCircleFiveIcon,
  NumberCircleSix: NumberCircleSixIcon,
  NumberCircleSeven: NumberCircleSevenIcon,
  NumberCircleEight: NumberCircleEightIcon,
  NumberCircleNine: NumberCircleNineIcon,
};

/**
 * `Object.hasOwn`, not a bare index. `GLYPH_COMPONENTS` is an object literal, so
 * it inherits Object.prototype: a bare `GLYPH_COMPONENTS['toString']` returns a
 * function — truthy, not a component — and React throws when it tries to render
 * it. Same for `constructor` and `valueOf`.
 *
 * Not reachable through the API today: `normalizeProjectGlyph` allowlists the
 * name against the catalogue on every write AND on the read path, and rejects
 * all of those keys (verified). This guard exists so the helper is safe on its
 * own terms rather than only because two other layers happen to hold — a future
 * caller passing a name from a URL, localStorage, or a cached payload would
 * otherwise turn a typo into a render crash.
 */
export function glyphComponent(name: string): Icon | null {
  return Object.hasOwn(GLYPH_COMPONENTS, name) ? (GLYPH_COMPONENTS[name] ?? null) : null;
}

/**
 * Search terms per glyph. Always includes the name lowercased, plus the words a
 * user would actually type — 'bin' and 'delete' for Trash, 'buy' and 'basket'
 * for ShoppingCart. Without these, search matches only the Phosphor identifier,
 * which is not a word most people would guess.
 */
export const GLYPH_SEARCH: Record<string, string[]> = {
  // Objects
  Trash: ['trash', 'bin', 'delete', 'remove'],
  ShoppingCart: ['shoppingcart', 'cart', 'buy', 'basket', 'shop', 'store'],
  Package: ['package', 'box', 'parcel', 'ship', 'delivery'],
  Briefcase: ['briefcase', 'work', 'business', 'job', 'case'],
  Gift: ['gift', 'present', 'reward', 'box'],
  Lightbulb: ['lightbulb', 'idea', 'bulb', 'light', 'tip'],
  Wrench: ['wrench', 'tool', 'fix', 'settings', 'repair'],
  Hammer: ['hammer', 'tool', 'build', 'construct'],
  Key: ['key', 'unlock', 'password', 'access', 'security'],
  Lock: ['lock', 'secure', 'security', 'password', 'privacy', 'locked'],
  Umbrella: ['umbrella', 'rain', 'weather', 'protect', 'insurance'],
  Trophy: ['trophy', 'award', 'win', 'winner', 'prize', 'achievement'],
  // Shapes
  Circle: ['circle', 'round', 'dot', 'shape'],
  Square: ['square', 'box', 'shape'],
  Triangle: ['triangle', 'shape'],
  Diamond: ['diamond', 'gem', 'shape', 'rhombus'],
  Hexagon: ['hexagon', 'shape', 'hex'],
  Star: ['star', 'favourite', 'favorite', 'rating'],
  Heart: ['heart', 'love', 'like', 'favourite', 'favorite'],
  Lightning: ['lightning', 'bolt', 'fast', 'power', 'energy', 'zap'],
  Spade: ['spade', 'card', 'cards', 'suit', 'poker'],
  Club: ['club', 'card', 'cards', 'suit', 'poker'],
  Cube: ['cube', '3d', 'box', 'shape', 'block'],
  Polygon: ['polygon', 'shape', 'geometry', 'vector'],
  // Files
  File: ['file', 'document', 'page'],
  FileText: ['filetext', 'document', 'text', 'doc', 'page'],
  Folder: ['folder', 'directory'],
  FolderOpen: ['folderopen', 'directory', 'open'],
  Note: ['note', 'memo', 'sticky'],
  Book: ['book', 'read', 'docs', 'manual', 'library'],
  Newspaper: ['newspaper', 'news', 'article', 'press'],
  Paperclip: ['paperclip', 'attach', 'attachment', 'clip'],
  Archive: ['archive', 'zip', 'storage', 'box', 'compress'],
  Notebook: ['notebook', 'journal', 'write', 'notes'],
  Files: ['files', 'documents', 'multiple', 'stack'],
  FolderPlus: ['folderplus', 'newfolder', 'add', 'create', 'directory'],
  // Actions
  Plus: ['plus', 'add', 'new', 'create'],
  Minus: ['minus', 'remove', 'subtract', 'less'],
  Copy: ['copy', 'duplicate', 'clone'],
  Check: ['check', 'done', 'tick', 'complete', 'ok'],
  X: ['x', 'close', 'cancel', 'cross', 'remove'],
  Pencil: ['pencil', 'edit', 'write', 'draw'],
  Bookmark: ['bookmark', 'save', 'mark', 'flag'],
  Eraser: ['eraser', 'delete', 'remove', 'undo', 'clear'],
  Scissors: ['scissors', 'cut', 'trim', 'snip'],
  LinkSimple: ['linksimple', 'link', 'url', 'chain', 'connect'],
  ShareNetwork: ['sharenetwork', 'share', 'network', 'send', 'distribute'],
  Clipboard: ['clipboard', 'paste', 'copy'],
  // Arrows
  ArrowUp: ['arrowup', 'up', 'north', 'increase'],
  ArrowDown: ['arrowdown', 'down', 'south', 'decrease'],
  ArrowLeft: ['arrowleft', 'left', 'back', 'west'],
  ArrowRight: ['arrowright', 'right', 'forward', 'next', 'east'],
  ArrowsClockwise: ['arrowsclockwise', 'refresh', 'reload', 'sync', 'retry'],
  ArrowSquareOut: ['arrowsquareout', 'external', 'open', 'link', 'launch'],
  TrendUp: ['trendup', 'growth', 'increase', 'chart', 'up'],
  TrendDown: ['trenddown', 'decline', 'decrease', 'chart', 'down'],
  ArrowsLeftRight: ['arrowsleftright', 'swap', 'exchange', 'toggle', 'switch'],
  ArrowUUpLeft: ['arrowuupleft', 'undo', 'back', 'revert'],
  ArrowsOut: ['arrowsout', 'expand', 'fullscreen', 'maximize', 'resize'],
  ArrowsIn: ['arrowsin', 'collapse', 'shrink', 'minimize', 'resize'],
  // Tech
  Code: ['code', 'develop', 'program', 'source'],
  Terminal: ['terminal', 'console', 'shell', 'cli', 'command'],
  Database: ['database', 'db', 'storage', 'data', 'sql'],
  Cloud: ['cloud', 'server', 'hosting', 'sky'],
  Cpu: ['cpu', 'chip', 'processor', 'compute', 'hardware'],
  Bug: ['bug', 'issue', 'defect', 'error', 'debug'],
  GitBranch: ['gitbranch', 'git', 'branch', 'repo', 'version'],
  Rocket: ['rocket', 'launch', 'ship', 'deploy', 'space'],
  Monitor: ['monitor', 'screen', 'display', 'computer'],
  DeviceMobile: ['devicemobile', 'phone', 'mobile', 'smartphone', 'app'],
  Keyboard: ['keyboard', 'type', 'keys', 'input'],
  Robot: ['robot', 'ai', 'bot', 'automation', 'machine'],
  // Nature
  Leaf: ['leaf', 'nature', 'plant', 'eco', 'green'],
  Tree: ['tree', 'nature', 'forest', 'plant'],
  Sun: ['sun', 'day', 'light', 'weather', 'bright'],
  Moon: ['moon', 'night', 'dark', 'sleep'],
  Drop: ['drop', 'water', 'liquid', 'rain'],
  Fire: ['fire', 'flame', 'hot', 'burn', 'trending'],
  Mountains: ['mountains', 'mountain', 'peak', 'nature', 'hike'],
  Planet: ['planet', 'space', 'world', 'globe', 'orbit'],
  Flower: ['flower', 'bloom', 'plant', 'nature', 'garden'],
  Cactus: ['cactus', 'plant', 'desert', 'succulent'],
  Snowflake: ['snowflake', 'snow', 'winter', 'cold', 'weather'],
  Rainbow: ['rainbow', 'colour', 'color', 'weather', 'pride'],
  // Symbols
  Hash: ['hash', 'number', 'tag', 'channel', 'pound'],
  At: ['at', 'mention', 'email', 'address'],
  Percent: ['percent', 'percentage', 'discount', 'rate'],
  Asterisk: ['asterisk', 'star', 'required', 'wildcard'],
  Question: ['question', 'help', 'ask', 'faq', 'unknown'],
  Warning: ['warning', 'alert', 'caution', 'danger'],
  Info: ['info', 'information', 'about', 'details'],
  Bell: ['bell', 'notification', 'alert', 'reminder'],
  Crown: ['crown', 'king', 'queen', 'royal', 'premium', 'vip'],
  Flag: ['flag', 'mark', 'report', 'country', 'milestone'],
  Medal: ['medal', 'award', 'achievement', 'win', 'honor'],
  Sparkle: ['sparkle', 'shine', 'magic', 'new', 'ai', 'clean'],
  // Food
  Carrot: ['carrot', 'vegetable', 'food', 'healthy'],
  Pizza: ['pizza', 'food', 'slice', 'italian'],
  Hamburger: ['hamburger', 'burger', 'food', 'fastfood'],
  IceCream: ['icecream', 'dessert', 'food', 'cold', 'sweet'],
  Coffee: ['coffee', 'drink', 'cafe', 'caffeine', 'cup'],
  BeerStein: ['beerstein', 'beer', 'drink', 'alcohol', 'pub'],
  Cookie: ['cookie', 'dessert', 'food', 'sweet', 'snack'],
  Cake: ['cake', 'dessert', 'birthday', 'celebration', 'sweet'],
  Egg: ['egg', 'food', 'breakfast'],
  Bread: ['bread', 'food', 'bakery', 'loaf'],
  Wine: ['wine', 'drink', 'alcohol', 'glass'],
  Martini: ['martini', 'cocktail', 'drink', 'alcohol', 'bar'],
  // Animals
  Dog: ['dog', 'pet', 'animal'],
  Cat: ['cat', 'pet', 'animal'],
  Bird: ['bird', 'animal', 'fly'],
  Butterfly: ['butterfly', 'insect', 'animal', 'nature'],
  Rabbit: ['rabbit', 'bunny', 'animal', 'pet'],
  Horse: ['horse', 'animal', 'ride'],
  Cow: ['cow', 'animal', 'farm', 'cattle'],
  PawPrint: ['pawprint', 'paw', 'pet', 'animal', 'print'],
  Fish: ['fish', 'animal', 'sea', 'aquarium', 'ocean'],
  Shrimp: ['shrimp', 'seafood', 'animal', 'ocean'],
  Feather: ['feather', 'bird', 'light', 'write'],
  Bone: ['bone', 'dog', 'pet', 'skeleton'],
  // Transport
  Car: ['car', 'vehicle', 'drive', 'auto'],
  Bus: ['bus', 'vehicle', 'transport', 'public'],
  Truck: ['truck', 'vehicle', 'delivery', 'cargo'],
  Train: ['train', 'vehicle', 'transport', 'rail'],
  Airplane: ['airplane', 'plane', 'flight', 'travel', 'fly'],
  Bicycle: ['bicycle', 'bike', 'cycle', 'ride'],
  Motorcycle: ['motorcycle', 'bike', 'ride', 'vehicle'],
  Boat: ['boat', 'ship', 'sail', 'water'],
  Scooter: ['scooter', 'ride', 'vehicle'],
  Taxi: ['taxi', 'cab', 'ride', 'car'],
  Van: ['van', 'vehicle', 'delivery'],
  Jeep: ['jeep', 'car', 'offroad', 'vehicle', 'suv'],
  // People
  User: ['user', 'person', 'profile', 'account'],
  Users: ['users', 'people', 'team', 'group'],
  Smiley: ['smiley', 'happy', 'face', 'emoji', 'smile'],
  SmileyMeh: ['smileymeh', 'meh', 'neutral', 'face', 'emoji'],
  SmileySad: ['smileysad', 'sad', 'face', 'emoji', 'unhappy'],
  Ghost: ['ghost', 'spooky', 'halloween', 'error', '404'],
  Alien: ['alien', 'space', 'ufo', 'extraterrestrial'],
  Baby: ['baby', 'infant', 'child', 'kid'],
  PersonSimpleRun: ['personsimplerun', 'run', 'running', 'exercise', 'fitness'],
  Hand: ['hand', 'stop', 'wave', 'gesture'],
  ThumbsUp: ['thumbsup', 'like', 'approve', 'good', 'vote'],
  Eye: ['eye', 'view', 'see', 'watch', 'visibility'],
  // Music
  MusicNote: ['musicnote', 'music', 'note', 'song', 'sound'],
  MusicNotes: ['musicnotes', 'music', 'notes', 'song', 'sound', 'playlist'],
  Guitar: ['guitar', 'music', 'instrument', 'band'],
  Microphone: ['microphone', 'mic', 'record', 'audio', 'podcast', 'sing'],
  SpeakerHigh: ['speakerhigh', 'speaker', 'volume', 'sound', 'audio'],
  Radio: ['radio', 'music', 'broadcast', 'audio', 'fm'],
  Playlist: ['playlist', 'music', 'queue', 'songs'],
  Metronome: ['metronome', 'music', 'tempo', 'beat', 'rhythm'],
  Waveform: ['waveform', 'audio', 'sound', 'wave', 'music'],
  Disc: ['disc', 'cd', 'vinyl', 'record', 'album'],
  Headphones: ['headphones', 'music', 'audio', 'listen', 'sound'],
  Equalizer: ['equalizer', 'audio', 'sound', 'mix', 'levels'],
  // Sport
  Basketball: ['basketball', 'sport', 'ball', 'nba'],
  Football: ['football', 'sport', 'nfl', 'ball', 'american'],
  SoccerBall: ['soccerball', 'soccer', 'football', 'sport', 'ball'],
  Baseball: ['baseball', 'sport', 'ball', 'mlb'],
  TennisBall: ['tennisball', 'tennis', 'sport', 'ball'],
  Barbell: ['barbell', 'gym', 'fitness', 'weights', 'workout'],
  Target: ['target', 'goal', 'aim', 'focus', 'bullseye'],
  Golf: ['golf', 'sport', 'club', 'ball'],
  Volleyball: ['volleyball', 'sport', 'ball'],
  PingPong: ['pingpong', 'tabletennis', 'sport', 'ball', 'paddle'],
  Racquet: ['racquet', 'racket', 'tennis', 'sport', 'badminton'],
  PersonSimpleSwim: ['personsimpleswim', 'swim', 'swimming', 'pool', 'sport'],
  // Money
  CurrencyDollar: ['currencydollar', 'dollar', 'money', 'price', 'cost', 'currency'],
  Wallet: ['wallet', 'money', 'payment', 'cash'],
  CreditCard: ['creditcard', 'card', 'payment', 'pay', 'money'],
  PiggyBank: ['piggybank', 'savings', 'budget', 'finance', 'save', 'money'],
  Coins: ['coins', 'money', 'cash', 'currency', 'change'],
  Receipt: ['receipt', 'invoice', 'bill', 'payment', 'order'],
  Bank: ['bank', 'finance', 'money', 'institution'],
  ChartLine: ['chartline', 'chart', 'graph', 'analytics', 'trend', 'stats'],
  Tag: ['tag', 'price', 'label', 'discount', 'sale'],
  ChartBar: ['chartbar', 'chart', 'graph', 'analytics', 'stats', 'bar'],
  ChartPie: ['chartpie', 'chart', 'graph', 'analytics', 'stats', 'pie'],
  Handshake: ['handshake', 'deal', 'partnership', 'agreement', 'business'],
  // Care
  CloudRain: ['cloudrain', 'rain', 'weather', 'storm'],
  CloudSnow: ['cloudsnow', 'snow', 'weather', 'winter'],
  CloudLightning: ['cloudlightning', 'lightning', 'storm', 'thunder', 'weather'],
  Wind: ['wind', 'weather', 'breeze', 'air'],
  Thermometer: ['thermometer', 'temperature', 'fever', 'weather', 'health'],
  Sunglasses: ['sunglasses', 'shades', 'summer', 'fashion'],
  Heartbeat: ['heartbeat', 'health', 'pulse', 'vitals', 'medical', 'ecg'],
  Pill: ['pill', 'medicine', 'drug', 'health', 'pharmacy'],
  FirstAid: ['firstaid', 'medical', 'health', 'emergency', 'kit'],
  Syringe: ['syringe', 'injection', 'vaccine', 'medical', 'shot'],
  Bandaids: ['bandaids', 'bandage', 'injury', 'medical'],
  Stethoscope: ['stethoscope', 'doctor', 'medical', 'health', 'checkup'],
  // Numbers
  NumberCircleZero: ['numbercirclezero', 'zero', '0', 'number'],
  NumberCircleOne: ['numbercircleone', 'one', '1', 'number'],
  NumberCircleTwo: ['numbercircletwo', 'two', '2', 'number'],
  NumberCircleThree: ['numbercirclethree', 'three', '3', 'number'],
  NumberCircleFour: ['numbercirclefour', 'four', '4', 'number'],
  NumberCircleFive: ['numbercirclefive', 'five', '5', 'number'],
  NumberCircleSix: ['numbercirclesix', 'six', '6', 'number'],
  NumberCircleSeven: ['numbercircleseven', 'seven', '7', 'number'],
  NumberCircleEight: ['numbercircleeight', 'eight', '8', 'number'],
  NumberCircleNine: ['numbercirclenine', 'nine', '9', 'number'],
};
