/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Agent } from "../../agent/base/Agent";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Session } from "../../session/base/Session";
import { EnumMemoryLogTypeField } from "./EnumMemoryLogTypeField";

@ObjectType()
class MemoryLog {
  @ApiProperty({
    required: false,
    type: () => Agent,
  })
  @ValidateNested()
  @Type(() => Agent)
  @IsOptional()
  agent?: Agent | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  relatedTask!: string | null;

  @ApiProperty({
    required: false,
    type: () => Session,
  })
  @ValidateNested()
  @Type(() => Session)
  @IsOptional()
  session?: Session | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  timestamp!: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumMemoryLogTypeField,
  })
  @IsEnum(EnumMemoryLogTypeField)
  @IsOptional()
  @Field(() => EnumMemoryLogTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { MemoryLog as MemoryLog };
