-- Migration: voice_call_turns
--
-- SAFETY HEADER (house rules -- see packages/db/MIGRATIONS.md#zero-downtime-rules).
set lock_timeout = '2s';
set statement_timeout = '30s';

-- The shared transcript of a live voice call. Both sides use it: the realtime
-- provider appends turns as they are spoken, and the Kortix session reads them
-- back through the voice MCP (`voice_read`).
--
-- `cursor` is an identity column, and it is the load-bearing one. The agent loop
-- is single-threaded, so it can never sit on a streaming read -- it has to ask
-- "what is new since X" and get an answer immediately. A monotonic cursor makes
-- that a plain indexed range scan and makes catch-up idempotent across
-- reconnects. Deliberately NOT ordered on created_at: two turns can share a
-- millisecond, and a wall-clock tie would silently drop one on the next poll.
--
-- Expand/contract checklist:
--   [x] CREATE TABLE only -- no existing table is touched, so no rewrite, no
--       backfill, and nothing to lock beyond the new relation.
--   [x] Indexes are built on the empty table in the same migration, so a plain
--       CREATE INDEX cannot block writes (nothing can write to a table that did
--       not exist a statement ago). The --concurrent escape hatch is for indexes
--       on populated tables and does not apply here.
--   [x] No FK to project_sessions or projects: a transcript outlives interest in
--       its session row, and a cascade delete would silently destroy history.
--       Orphans are acceptable; losing a call's record is not.
--   [x] No DROP/RENAME/ALTER TYPE -- nothing for old code to trip over.

CREATE TABLE "kortix"."voice_call_turns" (
  "cursor"     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "call_id"    text NOT NULL,
  "project_id" uuid NOT NULL,
  "session_id" text NOT NULL,
  "role"       varchar(16) NOT NULL,
  "speaker"    text,
  "text"       text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "voice_call_turns_role_check" CHECK ("role" IN ('user', 'agent'))
);

-- The only hot read pattern: "everything in this call after cursor X", in order.
CREATE INDEX "idx_voice_call_turns_call_cursor"
  ON "kortix"."voice_call_turns" ("call_id", "cursor");

-- Secondary: a session's whole voice history without knowing call ids.
CREATE INDEX "idx_voice_call_turns_session"
  ON "kortix"."voice_call_turns" ("session_id", "cursor");
