// Migration: project_sessions_account_active_index  (NON-TRANSACTIONAL -- CONCURRENTLY escape hatch)
//
// This file exists ONLY because CREATE INDEX CONCURRENTLY cannot run inside a
// transaction, and every plain .sql migration here runs inside the single batch
// transaction node-pg-migrate wraps around `pnpm migrate`. `pgm.noTransaction()`
// is the supported opt-out. See MIGRATIONS.md "Roll-forward safety".
//
// RESTORES A LOST INDEX. `countActiveProjectSessions` (apps/api/src/projects/lib/
// sessions.ts) COUNTs project_sessions by (account_id, status IN active-set) on
// EVERY session create. Two comments -- session-status.ts:5 and the schema at
// packages/db/src/schema/kortix.ts -- assert a partial index
// `idx_project_sessions_account_active` backs that COUNT and is "intentionally
// not declared" in the drizzle schema so `db:generate` won't fight it. It is not
// in the migration lineage:
//
//   - created 2026-06-17 by commit c11be54696, as a file under packages/db/
//     drizzle/ -- NOT packages/db/migrations/, which is what the runner executes;
//   - the 2026-06-21 baseline was generated by INTROSPECTING LIVE PRODUCTION and
//     captures indexes (31 partial ones among them), yet lists only five
//     project_sessions indexes: _account, _created_by, _project, _project_branch,
//     _status. This one is absent -- i.e. it was not live in prod four days after
//     it was written;
//   - the original file is gone (removed in the rebaseline) and nothing since
//     recreates it.
//
// So the account-wide concurrency cap has most likely been scanning instead of
// using an index. This matters more now that the per-END-USER cap in this same
// PR adds a SECOND COUNT to that hot path.
//
// IF NOT EXISTS makes this a no-op wherever the index does already exist (e.g. if
// it was ever applied by hand), so it is safe regardless of which is true -- no
// live pg_indexes check needed before shipping it.
//
// The status predicate mirrors ACTIVE_SESSION_STATUSES (apps/api/src/projects/
// lib/session-status.ts); if that list changes, this predicate must change with
// it or the COUNT silently stops using the index -- exactly how it got lost.
//
// Purely additive: a new non-unique partial btree, no code depends on its
// absence, and CREATE INDEX CONCURRENTLY never blocks writes.

export const shorthands = undefined;

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
export const up = (pgm) => {
  pgm.noTransaction();
  // IMPORTANT: separate pgm.sql() calls -- a multi-statement simple query is an
  // implicit transaction block, which silently defeats noTransaction().
  pgm.sql(`set lock_timeout = '2s'`);
  pgm.sql(`
    create index concurrently if not exists idx_project_sessions_account_active
      on kortix.project_sessions (account_id)
      where status in ('queued', 'branching', 'provisioning', 'running')
  `);
};

// Most CONCURRENTLY migrations are one-way in practice (see MIGRATIONS.md).
export const down = false;
