-- Migration: isolate_existing_llm_credentials
set lock_timeout = '2s';
set statement_timeout = '30s';

-- These names are the native provider credential names in the bundled LLM
-- catalog. New writes use the live catalog in the API. This point-in-time
-- backfill prevents existing provider credentials from entering new sandboxes.
with llm_secret_names(name) as (
  values
    ('302AI_API_KEY'),
    ('ABACUS_API_KEY'),
    ('ABLIT_KEY'),
    ('AICORE_SERVICE_KEY'),
    ('AIHUBMIX_API_KEY'),
    ('AI_GATEWAY_API_KEY'),
    ('AI_ROUTER_API_KEY'),
    ('ALIBABA_CODING_PLAN_API_KEY'),
    ('ALIBABA_TOKEN_PLAN_API_KEY'),
    ('AMBIENT_API_KEY'),
    ('ANTHROPIC_API_KEY'),
    ('ANYAPI_API_KEY'),
    ('ATOMIC_CHAT_API_KEY'),
    ('AURIKO_API_KEY'),
    ('AWS_BEARER_TOKEN_BEDROCK'),
    ('AWS_REGION'),
    ('AZURE_COGNITIVE_SERVICES_RESOURCE_NAME'),
    ('AZURE_RESOURCE_NAME'),
    ('BAILING_API_TOKEN'),
    ('BASETEN_API_KEY'),
    ('BERGET_API_KEY'),
    ('BLUECLAW_API_KEY'),
    ('CEREBRAS_API_KEY'),
    ('CHUTES_API_KEY'),
    ('CLARIFAI_PAT'),
    ('CLAUDINIO_API_KEY'),
    ('CLOUDFERRO_SHERLOCK_API_KEY'),
    ('CLOUDFLARE_ACCOUNT_ID'),
    ('CLOUDFLARE_API_TOKEN'),
    ('COHERE_API_KEY'),
    ('CORTECS_API_KEY'),
    ('CROF_API_KEY'),
    ('CROSSMODEL_API_KEY'),
    ('DAOXE_API_KEY'),
    ('DASHSCOPE_API_KEY'),
    ('DATABRICKS_HOST'),
    ('DEEPINFRA_API_KEY'),
    ('DEEPSEEK_API_KEY'),
    ('DIGITALOCEAN_ACCESS_TOKEN'),
    ('DINFERENCE_API_KEY'),
    ('DRUN_API_KEY'),
    ('EBCLOUD_API_KEY'),
    ('EMPIRIOLABS_API_KEY'),
    ('EVROC_API_KEY'),
    ('FASTROUTER_API_KEY'),
    ('FIREWORKS_API_KEY'),
    ('FREEMODEL_API_KEY'),
    ('FRIENDLI_TOKEN'),
    ('FROGBOT_API_KEY'),
    ('GITHUB_TOKEN'),
    ('GITLAB_TOKEN'),
    ('GMICLOUD_API_KEY'),
    ('GROQ_API_KEY'),
    ('HELICONE_API_KEY'),
    ('HF_TOKEN'),
    ('HPC_AI_API_KEY'),
    ('IFLOW_API_KEY'),
    ('INCEPTION_API_KEY'),
    ('INCEPTRON_API_KEY'),
    ('INFERENCE_API_KEY'),
    ('INFERX_API_KEY'),
    ('IOINTELLIGENCE_API_KEY'),
    ('JIEKOU_API_KEY'),
    ('KENARI_API_KEY'),
    ('KILO_API_KEY'),
    ('KIMI_API_KEY'),
    ('KUAE_API_KEY'),
    ('LILAC_API_KEY'),
    ('LLAMA_API_KEY'),
    ('LLMGATEWAY_API_KEY'),
    ('LLMTR_API_KEY'),
    ('LMSTUDIO_API_KEY'),
    ('LONGCAT_API_KEY'),
    ('LUCIDQUERY_API_KEY'),
    ('LYNKR_API_KEY'),
    ('MEGANOVA_API_KEY'),
    ('MERGE_GATEWAY_API_KEY'),
    ('META_MODEL_API_KEY'),
    ('MINIMAX_API_KEY'),
    ('MISTRAL_API_KEY'),
    ('MIXLAYER_API_KEY'),
    ('MOARK_API_KEY'),
    ('MODELSCOPE_API_KEY'),
    ('MODEL_ORACLE_API_KEY'),
    ('MOONSHOT_API_KEY'),
    ('MORPH_API_KEY'),
    ('NANO_GPT_API_KEY'),
    ('NEARAI_API_KEY'),
    ('NEBIUS_API_KEY'),
    ('NEON_AI_GATEWAY_BASE_URL'),
    ('NEURALWATT_API_KEY'),
    ('NOVA_API_KEY'),
    ('NOVITA_API_KEY'),
    ('NVIDIA_API_KEY'),
    ('OLLAMA_API_KEY'),
    ('OPENAI_API_KEY'),
    ('OPENCODE_API_KEY'),
    ('OPENROUTER_API_KEY'),
    ('ORCAROUTER_API_KEY'),
    ('OVHCLOUD_API_KEY'),
    ('PERPLEXITY_API_KEY'),
    ('PIONEER_API_KEY'),
    ('POE_API_KEY'),
    ('POOLSIDE_API_KEY'),
    ('PRIVATEMODE_API_KEY'),
    ('QIHANG_API_KEY'),
    ('QINIU_API_KEY'),
    ('REGOLO_API_KEY'),
    ('REQUESTY_API_KEY'),
    ('ROUTING_RUN_API_KEY'),
    ('SAKANA_API_KEY'),
    ('SARVAM_API_KEY'),
    ('SCALEWAY_API_KEY'),
    ('SILICONFLOW_API_KEY'),
    ('SILICONFLOW_CN_API_KEY'),
    ('SNOWFLAKE_ACCOUNT'),
    ('STACKIT_API_KEY'),
    ('STEPFUN_API_KEY'),
    ('SUBCONSCIOUS_API_KEY'),
    ('SUBMODEL_INSTAGEN_ACCESS_KEY'),
    ('SYNTHETIC_API_KEY'),
    ('TENCENT_CODING_PLAN_API_KEY'),
    ('TENCENT_TOKENHUB_API_KEY'),
    ('TENCENT_TOKEN_PLAN_API_KEY'),
    ('THEGRIDAI_API_KEY'),
    ('TINFOIL_API_KEY'),
    ('TINKER_API_KEY'),
    ('TOGETHER_API_KEY'),
    ('TRUSTEDROUTER_API_KEY'),
    ('UMANS_AI_API_KEY'),
    ('UMANS_AI_CODING_PLAN_API_KEY'),
    ('UNOROUTER_API_KEY'),
    ('UPSTAGE_API_KEY'),
    ('V0_API_KEY'),
    ('VENICE_API_KEY'),
    ('VIVGRID_API_KEY'),
    ('VULTR_API_KEY'),
    ('WAFER_API_KEY'),
    ('WANDB_API_KEY'),
    ('XAI_API_KEY'),
    ('XIAOMI_API_KEY'),
    ('XPERSONA_API_KEY'),
    ('ZELDOC_API_KEY'),
    ('ZENIFRA_AI_KEY'),
    ('ZENMUX_API_KEY'),
    ('ZHIPU_API_KEY')
)
update "kortix"."project_secrets" as secret
set
  "strategy" = 'broker',
  "consumer" = 'llm_gateway',
  "egress_policy" = null,
  "handle_prefix" = null,
  "rotated_at" = null,
  "updated_at" = now()
from llm_secret_names
where
  secret."name" = llm_secret_names.name
  and (
    secret."strategy" <> 'broker'
    or secret."consumer" is distinct from 'llm_gateway'::"kortix"."project_secret_consumer"
    or secret."egress_policy" is not null
    or secret."handle_prefix" is not null
  );
