/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Tool } from "./Tool";
import { ToolCountArgs } from "./ToolCountArgs";
import { ToolFindManyArgs } from "./ToolFindManyArgs";
import { ToolFindUniqueArgs } from "./ToolFindUniqueArgs";
import { DeleteToolArgs } from "./DeleteToolArgs";
import { ToolService } from "../tool.service";
@graphql.Resolver(() => Tool)
export class ToolResolverBase {
  constructor(protected readonly service: ToolService) {}

  async _toolsMeta(
    @graphql.Args() args: ToolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Tool])
  async tools(@graphql.Args() args: ToolFindManyArgs): Promise<Tool[]> {
    return this.service.tools(args);
  }

  @graphql.Query(() => Tool, { nullable: true })
  async tool(@graphql.Args() args: ToolFindUniqueArgs): Promise<Tool | null> {
    const result = await this.service.tool(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Tool)
  async deleteTool(@graphql.Args() args: DeleteToolArgs): Promise<Tool | null> {
    try {
      return await this.service.deleteTool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
