import { Card, CardContent } from '@/components/ui/card';


export default function TermsPage() {
  return (
    <main className="bg-background flex min-h-screen w-full flex-col items-center justify-center">
      <section className="w-full pb-20">
        <div className="flex w-full flex-col items-center px-6 pt-10">
          <div className="mx-auto w-full max-w-4xl">
            <div className="mb-10 flex items-center justify-center">
              <h1 className="text-primary text-center text-3xl font-medium tracking-tighter md:text-4xl">
                Terms of Service
              </h1>
            </div>
            <Card>
              <CardContent className="p-8">
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  <p className="text-muted-foreground mb-6 text-sm">Last updated: August 3, 2026</p>

                  <p className="text-muted-foreground mb-6">
                    These Terms of Service (the <strong>&ldquo;Terms&rdquo;</strong>) are a legal agreement between Kortix AI Corp, a Delaware corporation (<strong>&ldquo;Kortix,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo;</strong> or <strong>&ldquo;our&rdquo;</strong>), and the person or organization accepting these Terms (<strong>&ldquo;Customer,&rdquo; &ldquo;you,&rdquo;</strong> or <strong>&ldquo;your&rdquo;</strong>). They govern access to and use of the Services.
                  </p>

                  <p className="text-muted-foreground mb-6">
                    If you use the Services for an organization, you accept these Terms for that organization and represent that you have authority to bind it. If you do not have that authority, or do not agree to these Terms, do not use the Services.
                  </p>

                  <p className="text-muted-foreground mb-6">
                    You accept these Terms when you click to accept them, create an Account, sign or accept an Order, or access or use the Services. If you and Kortix have signed a separate agreement expressly governing the same Services, that agreement controls to the extent it conflicts with these Terms.
                  </p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">1. Definitions</h2>
                  <ul className="text-muted-foreground mb-6 space-y-1">
                    <li><strong>&ldquo;Account&rdquo;</strong> means an account through which Customer or its Users access the Services.</li>
                    <li><strong>&ldquo;Affiliate&rdquo;</strong> means an entity that directly or indirectly controls, is controlled by, or is under common control with a party.</li>
                    <li><strong>&ldquo;Agent&rdquo;</strong> means an AI-enabled workflow, process, or software agent configured or operated through the Services that may generate Outputs, use tools, access systems, or take actions with varying degrees of autonomy.</li>
                    <li><strong>&ldquo;Applicable Law&rdquo;</strong> means laws, regulations, binding orders, and legally enforceable governmental requirements applicable to a party or the Services.</li>
                    <li><strong>&ldquo;AUP&rdquo;</strong> means the acceptable-use rules in Section 5.</li>
                    <li><strong>&ldquo;Customer Data&rdquo;</strong> means data, content, files, prompts, instructions, credentials, configurations, code, records, and other materials submitted to or made available to the Services by or for Customer or its Users.</li>
                    <li><strong>&ldquo;DPA&rdquo;</strong> means a data processing addendum entered into by the parties.</li>
                    <li><strong>&ldquo;Fees&rdquo;</strong> means amounts payable for Services under an Order or the applicable checkout or pricing page.</li>
                    <li><strong>&ldquo;Order&rdquo;</strong> means an order form, statement of work (SOW), online purchase, plan selection, or other ordering document accepted by both parties.</li>
                    <li><strong>&ldquo;Output&rdquo;</strong> means content or a result generated by the Services in response to Customer Data.</li>
                    <li><strong>&ldquo;Professional Services&rdquo;</strong> means implementation, configuration, integration, migration, training, consulting, or similar services identified in an Order.</li>
                    <li><strong>&ldquo;Services&rdquo;</strong> means Kortix&rsquo;s hosted platforms, managed cloud subscriptions, APIs, SDKs, software made available with a subscription, Agents, support, Professional Services, websites, and related offerings.</li>
                    <li><strong>&ldquo;Third-Party Services&rdquo;</strong> means models, APIs, data sources, websites, software, infrastructure, connectors, plugins, MCP servers, and other products or services supplied by third parties.</li>
                    <li><strong>&ldquo;User&rdquo;</strong> means an individual authorized by Customer to use the Services through Customer&rsquo;s Account.</li>
                  </ul>

                  <p className="text-muted-foreground mb-6">
                    These Terms are framework terms that may govern one or more Orders. Each Order and these Terms form the <strong>&ldquo;Agreement.&rdquo;</strong> If documents conflict, they control in this order: (1) mandatory data-transfer terms; (2) the DPA; (3) a signed Order; (4) these Terms; (5) Documentation. A customer purchase order is for administrative convenience only.
                  </p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">2. Eligibility and Accounts</h2>
                  <p className="text-muted-foreground mb-4">You must be at least 18 years old and legally able to enter into a contract. The Services are offered for business and professional use, not household or consumer use.</p>
                  <p className="text-muted-foreground mb-4">Customer is responsible for selecting its Users, assigning roles and permissions, and all activity under its Account.</p>
                  <p className="text-muted-foreground mb-6">Customer and its Users must keep passwords, tokens, API keys, and credentials confidential and promptly revoke compromised credentials.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">3. Subscription and Access</h2>
                  <p className="text-muted-foreground mb-4">Kortix grants Customer a limited, non-exclusive, non-transferable, non-sublicensable right to access and use the Services for Customer&rsquo;s internal business purposes.</p>
                  <p className="text-muted-foreground mb-4">Unless an Order says otherwise, subscriptions are provided as managed cloud Services operated by or for Kortix. Customer may use Kortix APIs and SDKs within documented limits.</p>
                  <p className="text-muted-foreground mb-4">An Order may permit Customer to connect its own model, API, cloud, or infrastructure credentials (BYO Keys), or to deploy identified Kortix software in a Customer-controlled environment. Customer is responsible for its BYO Keys and environment.</p>
                  <p className="text-muted-foreground mb-6">Trials and beta features may be incomplete, changed, or discontinued at any time and are provided &ldquo;AS IS.&rdquo;</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">4. Customer Responsibilities</h2>
                  <p className="text-muted-foreground mb-4">Customer is responsible for Customer Data, instructions to Agents, and decisions based on Outputs. Customer represents that it has all rights and lawful bases needed for Kortix to process Customer Data.</p>
                  <p className="text-muted-foreground mb-4">AI systems are probabilistic. Outputs may be inaccurate, incomplete, or unsuitable. Customer must evaluate Outputs and maintain meaningful human review proportionate to the consequences of error.</p>
                  <p className="text-muted-foreground mb-6">Customer is responsible for compliance with Applicable Law, the Agreement, and Third-Party Service terms.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">5. Acceptable Use</h2>
                  <p className="text-muted-foreground mb-4">Customer will not use the Services unlawfully, to violate others&rsquo; rights, to generate malware, to bypass security controls, to exploit minors, to make high-impact decisions without human review, to use in safety-critical systems, to train competing models via systematic extraction, to reverse engineer, or to interfere with the Services.</p>
                  <p className="text-muted-foreground mb-6">Kortix may investigate suspected violations and remove or restrict affected content or access.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">6. Fees, Payment, and Taxes</h2>
                  <p className="text-muted-foreground mb-4">Customer will pay the Fees shown on the applicable Order or checkout. Enterprise subscription Fees are invoiced annually in advance, due within 30 days (Net 30).</p>
                  <p className="text-muted-foreground mb-4">Enterprise subscriptions auto-renew for successive one-year terms unless either party gives 60 days&rsquo; notice. Fees exclude sales, use, VAT, and similar taxes; Customer pays those.</p>
                  <p className="text-muted-foreground mb-6">Fees are non-cancelable and non-refundable except where the Agreement or Applicable Law requires.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">7. Customer Data, Outputs, and Usage Data</h2>
                  <p className="text-muted-foreground mb-4">Customer retains all rights in Customer Data. Kortix will not use Customer Data or Outputs to train generalized AI models unless Customer gives express permission.</p>
                  <p className="text-muted-foreground mb-4">Customer owns its Outputs to the extent permitted by law. Kortix assigns any rights it may have in those Outputs.</p>
                  <p className="text-muted-foreground mb-6">Kortix may collect and use Usage Data to operate, secure, and improve the Services, disclosed externally only in aggregated or de-identified form.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">8. Privacy, Security, and Data Processing</h2>
                  <p className="text-muted-foreground mb-4">Kortix&rsquo;s Privacy Policy describes its handling of personal information. If Kortix processes personal data on Customer&rsquo;s behalf, the parties will enter into a DPA.</p>
                  <p className="text-muted-foreground mb-6">Customer is responsible for security within its control, including User management, role configuration, and credential protection.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">9. Confidentiality</h2>
                  <p className="text-muted-foreground mb-6">Each party will protect the other&rsquo;s non-public information with at least reasonable care and use it only to perform under the Agreement.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">10. Intellectual Property and Open Source</h2>
                  <p className="text-muted-foreground mb-4">Kortix retains all rights in the Services, Documentation, and related technology. Customer owns Deliverables expressly identified in an Order as assigned to Customer.</p>
                  <p className="text-muted-foreground mb-6">Open-source components are governed by their separate licenses. Public availability of source code does not grant rights beyond the applicable license.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">11. Warranties and Disclaimers</h2>
                  <p className="text-muted-foreground mb-4">Kortix warrants that paid Services will materially conform to Documentation and Professional Services will be performed professionally. Exclusive remedy: correction or prorated refund.</p>
                  <p className="text-muted-foreground mb-6">Services are provided &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE.&rdquo; Kortix disclaims all implied warranties to the maximum extent permitted by law.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">12. Third-Party Services</h2>
                  <p className="text-muted-foreground mb-6">Customer&rsquo;s use of Third-Party Services is governed by Customer&rsquo;s agreement with that provider. Kortix is not responsible for Third-Party Services.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">13. Indemnification</h2>
                  <p className="text-muted-foreground mb-4">Kortix will defend Customer against third-party IP claims for authorized use of paid Services. Customer will defend Kortix against claims arising from Customer Data, AUP violations, or Customer-selected Third-Party Services.</p>
                  <p className="text-muted-foreground mb-6">Each party must promptly notify the other, give control of defense, and cooperate.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">14. Limitation of Liability</h2>
                  <p className="text-muted-foreground mb-4">Each party&rsquo;s total aggregate liability will not exceed the Fees paid in the 12 months before the event. Increased claims (2x cap) apply to DPA/security, confidentiality, and indemnification breaches.</p>
                  <p className="text-muted-foreground mb-6">Neither party is liable for indirect, consequential, or punitive damages. Fraud and willful misconduct are uncapped.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">15. Term, Renewal, Termination, and Data Export</h2>
                  <p className="text-muted-foreground mb-4">Either party may terminate for material breach with 30 days&rsquo; notice (10 days for nonpayment). Customer may cancel self-serve subscriptions at the end of the current period.</p>
                  <p className="text-muted-foreground mb-6">Customer may export Customer Data during the term and for 30 days after termination.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">16. Modifications</h2>
                  <p className="text-muted-foreground mb-6">For self-serve Services, Kortix may update these Terms with advance notice. Material changes take effect at the next renewal or 30 days after notice. For signed Orders, amendments must be in writing.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">17. General Terms</h2>
                  <p className="text-muted-foreground mb-4">Delaware law governs the Agreement. Delaware courts have exclusive jurisdiction. Each party waives jury trial.</p>
                  <p className="text-muted-foreground mb-4">Notices to Kortix: legal@kortix.com or Kortix AI Corp, 701 Tillery Street, Unit 12-2521, Austin, TX 78702.</p>
                  <p className="text-muted-foreground mb-6">The parties are independent contractors. The Agreement is the entire agreement. Electronic signatures have the same effect as originals.</p>

                  <h2 className="mb-4 mt-8 text-lg font-medium tracking-tight">18. Contact</h2>
                  <p className="text-muted-foreground mb-2">Questions: <a href="mailto:info@kortix.com" className="text-primary hover:underline">info@kortix.com</a></p>
                  <p className="text-muted-foreground mb-2">Legal: <a href="mailto:legal@kortix.com" className="text-primary hover:underline">legal@kortix.com</a></p>
                  <p className="text-muted-foreground mb-6">Security: <a href="mailto:security@kortix.com" className="text-primary hover:underline">security@kortix.com</a></p>

                  <hr className="my-6 border-border" />
                  <p className="text-muted-foreground text-xs">
                    Portions of these Terms are adapted from the Common Paper Cloud Service Agreement Standard Terms Version 2.1 and the Common Paper Professional Services Agreement Standard Terms Version 1.1, each made available under the <a href="https://creativecommons.org/licenses/by/4.0/" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">Creative Commons Attribution 4.0 International License</a>. Common Paper has not endorsed Kortix or these modified Terms.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </main>
  );
}
