import { createHash } from 'node:crypto';

export const KORTIX_WEB_ORIGIN = 'https://kortix.com';
export const KORTIX_API_ORIGIN = 'https://api.kortix.com/v1';
export const KORTIX_OAUTH_ISSUER = 'https://jbriwassebxdwoieikga.supabase.co/auth/v1';
export const DISCOVERY_CACHE_CONTROL = 'public, max-age=3600, s-maxage=3600';
export const MCP_PROTOCOL_VERSION = '2025-03-26';
export const MCP_SERVER_VERSION = '1.0.0';

export const API_CATALOG = {
  linkset: [
    {
      anchor: KORTIX_API_ORIGIN,
      'service-desc': [
        {
          href: `${KORTIX_API_ORIGIN}/openapi.json`,
          type: 'application/json',
          title: 'Kortix OpenAPI document',
        },
      ],
      'service-doc': [
        {
          href: `${KORTIX_WEB_ORIGIN}/docs`,
          type: 'text/html',
          title: 'Kortix API documentation',
        },
      ],
      status: [
        {
          href: `${KORTIX_API_ORIGIN}/health`,
          type: 'application/json',
          title: 'Kortix API health',
        },
      ],
    },
  ],
} as const;

/**
 * Kortix accepts Supabase access JWTs on protected API routes. This document
 * mirrors the production issuer's public OIDC discovery metadata. The issuer
 * remains the canonical Supabase issuer so clients validate the correct `iss`.
 */
export const OAUTH_AUTHORIZATION_SERVER_METADATA = {
  issuer: KORTIX_OAUTH_ISSUER,
  authorization_endpoint: `${KORTIX_OAUTH_ISSUER}/oauth/authorize`,
  token_endpoint: `${KORTIX_OAUTH_ISSUER}/oauth/token`,
  jwks_uri: `${KORTIX_OAUTH_ISSUER}/.well-known/jwks.json`,
  userinfo_endpoint: `${KORTIX_OAUTH_ISSUER}/oauth/userinfo`,
  scopes_supported: ['openid', 'profile', 'email', 'phone'],
  response_types_supported: ['code'],
  response_modes_supported: ['query'],
  grant_types_supported: ['authorization_code', 'refresh_token'],
  subject_types_supported: ['public'],
  id_token_signing_alg_values_supported: ['RS256', 'HS256', 'ES256'],
  token_endpoint_auth_methods_supported: ['client_secret_basic', 'client_secret_post', 'none'],
  code_challenge_methods_supported: ['S256'],
  agent_auth: {
    skill: `${KORTIX_WEB_ORIGIN}/auth.md`,
    register_uri: `${KORTIX_WEB_ORIGIN}/cli/authorize`,
    identity_types_supported: ['user_authorization'],
    user_authorization: {
      credential_types_supported: ['kortix_personal_access_token'],
      authorization_uri: `${KORTIX_WEB_ORIGIN}/cli/authorize`,
      provisioning_endpoint: `${KORTIX_API_ORIGIN}/accounts/tokens`,
      revocation_uri: `${KORTIX_API_ORIGIN}/accounts/tokens/{token_id}`,
    },
  },
} as const;

export function oauthProtectedResourceMetadata(resource = KORTIX_WEB_ORIGIN) {
  return {
    resource,
    authorization_servers: [KORTIX_OAUTH_ISSUER],
    scopes_supported: ['openid', 'profile', 'email'],
    bearer_methods_supported: ['header'],
    resource_documentation: `${resource}/docs`,
  } as const;
}

export const AUTH_MD = `# Kortix auth.md

Kortix agents can authenticate to the protected API with a user-authorized OAuth access token or a Kortix personal access token.

## Discover the protected resource

- Protected resource metadata: /.well-known/oauth-protected-resource
- OAuth authorization server metadata: /.well-known/oauth-authorization-server
- API catalog: /.well-known/api-catalog
- OpenAPI document: ${KORTIX_API_ORIGIN}/openapi.json

## OAuth authorization code flow

1. Read the authorization server metadata.
2. Use the authorization code flow with PKCE S256.
3. Request only the scopes required for the task.
4. Send the access token as \`Authorization: Bearer <token>\`.

Register an OAuth client yourself at Account → Tokens → OAuth apps, or \`POST /v1/accounts/{accountId}/iam/oauth-clients\` (needs \`token.create\`). Authorization-server metadata for the Kortix-native provider: ${KORTIX_API_ORIGIN.replace(/\/v1$/, '')}/.well-known/oauth-authorization-server.

## Agent registration with a personal access token

Audience: an AI agent acting for an existing Kortix user.

- Registration method: user-authorized browser flow
- Registration URI: /cli/authorize
- Credential type: \`kortix_personal_access_token\`
- Provisioning endpoint: \`POST ${KORTIX_API_ORIGIN}/accounts/tokens\`
- Revocation endpoint: \`DELETE ${KORTIX_API_ORIGIN}/accounts/tokens/{token_id}\`

1. Install the Kortix CLI from ${KORTIX_WEB_ORIGIN}/install.
2. Run \`kortix login\`.
3. Open the registration URI generated by the CLI.
4. Sign in as the Kortix user who owns the agent action.
5. Approve the browser authorization request.
6. Send the resulting token as \`Authorization: Bearer <token>\`.

The CLI supplies required query parameters to \`/cli/authorize\`. Do not open the registration URI without the CLI request.

Never put a token in a URL, repository, log, or chat message.

## Unsupported registration methods

Kortix does not accept anonymous agent registration, ID-JAG assertions, or automated verified-email claims.
`;

export const KORTIX_PUBLIC_CONTENT_SKILL = `---
name: kortix-public-content
description: Discover and read Kortix public documentation through standards-based HTTP and MCP endpoints.
---

# Kortix Public Content

Use this skill to discover Kortix APIs and public product documentation.

## Discover APIs

1. Fetch ${KORTIX_WEB_ORIGIN}/.well-known/api-catalog.
2. Follow the service-desc relation for the OpenAPI document.
3. Follow the service-doc relation for human-readable documentation.

## Request Markdown

Send \`Accept: text/markdown\` to a supported public HTML URL.
The response uses \`Content-Type: text/markdown; charset=utf-8\`.

## Use MCP

Connect to ${KORTIX_WEB_ORIGIN}/mcp with the Streamable HTTP transport.
Call \`list_public_content\` before \`get_public_markdown\`.

## Authenticate

Read ${KORTIX_WEB_ORIGIN}/auth.md before calling protected API routes.
Never send credentials to a host outside the discovered Kortix endpoints.
`;

export function agentSkillsIndex() {
  const digest = createHash('sha256').update(KORTIX_PUBLIC_CONTENT_SKILL).digest('hex');
  return {
    $schema: 'https://schemas.agentskills.io/discovery/0.2.0/schema.json',
    skills: [
      {
        name: 'kortix-public-content',
        type: 'skill-md',
        description: 'Discover and read Kortix public API and documentation resources.',
        url: `${KORTIX_WEB_ORIGIN}/.well-known/agent-skills/kortix-public-content/SKILL.md`,
        digest: `sha256:${digest}`,
      },
    ],
  } as const;
}

/** Compatibility card for the discovery scanner's pre-SEP-2127 field names. */
export const MCP_WELL_KNOWN_SERVER_CARD = {
  serverInfo: {
    name: 'kortix-public-content',
    version: MCP_SERVER_VERSION,
  },
  transport: {
    type: 'streamable-http',
    endpoint: `${KORTIX_WEB_ORIGIN}/mcp`,
  },
  endpoint: `${KORTIX_WEB_ORIGIN}/mcp`,
  capabilities: {
    tools: true,
    resources: true,
    prompts: false,
  },
} as const;

/** Current SEP-2127 server-card shape. */
export const MCP_SERVER_CARD = {
  $schema: 'https://static.modelcontextprotocol.io/schemas/v1/server-card.schema.json',
  name: 'com.kortix/public-content',
  version: MCP_SERVER_VERSION,
  title: 'Kortix Public Content',
  description: 'Search and read Kortix public documentation and API metadata.',
  websiteUrl: KORTIX_WEB_ORIGIN,
  repository: {
    url: 'https://github.com/kortix-ai/suna',
    source: 'github',
  },
  remotes: [
    {
      type: 'streamable-http',
      url: `${KORTIX_WEB_ORIGIN}/mcp`,
      supportedProtocolVersions: [MCP_PROTOCOL_VERSION],
    },
  ],
} as const;

export const AI_CATALOG = {
  specVersion: '1.0',
  entries: [
    {
      identifier: 'urn:air:kortix.com:mcp:public-content',
      type: 'application/mcp-server-card+json',
      url: `${KORTIX_WEB_ORIGIN}/mcp/server-card`,
    },
  ],
} as const;

export function discoveryJson(
  value: unknown,
  contentType = 'application/json; charset=utf-8',
): Response {
  return new Response(`${JSON.stringify(value, null, 2)}\n`, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': DISCOVERY_CACHE_CONTROL,
      'Content-Type': contentType,
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
