// Thin re-export — the gateway observability client now lives in the SDK
// (packages/sdk/src/platform/projects-client/gateway.ts). Kept here under the
// original names so the many consumers under features/workspace/customize
// don't need to change their import paths.

export {
  createGatewayKey,
  deleteGatewayBudget,
  getGatewayBreakdown,
  getGatewayBudgets,
  getGatewayErrors,
  getGatewayKeys,
  getGatewayLog,
  getGatewayOverview,
  getGatewaySeries,
  getGatewaySessions,
  listGatewayLogs,
  revokeGatewayKey,
  runGatewayPlayground,
  setGatewayBudget,
  type CreatedGatewayKey,
  type GatewayBreakdown,
  type GatewayBudgetRow,
  type GatewayBudgetsResponse,
  type GatewayErrorStat,
  type GatewayErrorsResponse,
  type GatewayKeyRow,
  type GatewayLogDetail,
  type GatewayLogRow,
  type GatewayLogsResponse,
  type GatewayMemberSpend,
  type GatewayModelGenerationConfig,
  type GatewayModelStat,
  type GatewayOverview,
  type GatewayPlaygroundResponse,
  type GatewayPlaygroundResult,
  type GatewaySeries,
  type GatewaySeriesPoint,
  type GatewaySessionStat,
  type GatewaySessions,
  type SetGatewayBudgetInput,
} from '@kortix/sdk';
