// GENERATED by scripts/generate-wallpapers.mjs — do not edit by hand.
// Re-run it after changing any wallpaper composition.

export interface WallpaperDownloadFile {
  /** Human size label shown on the download chip, e.g. `5K`. */
  label: string;
  width: number;
  height: number;
  href: string;
  file: string;
  bytes: number;
}

export interface WallpaperDownload {
  /** `mark` = the brand wallpaper; `product` = a wallpaper you can set on a Kortix home. */
  group: 'mark' | 'product';
  id: string;
  name: string;
  theme: 'light' | 'dark';
  /** Small JPEG of this exact composition, for the card on /design-system. */
  preview: string;
  files: WallpaperDownloadFile[];
}

export const WALLPAPER_DOWNLOADS: WallpaperDownload[] = [
  {
    group: 'mark',
    id: 'mark',
    name: 'Kortix Mark',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-mark-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-mark-light-5120x2880.png',
        file: 'kortix-mark-light-5120x2880.png',
        bytes: 55410,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/kortix-mark-light-3840x2160.png',
        file: 'kortix-mark-light-3840x2160.png',
        bytes: 33154,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/kortix-mark-light-2560x1440.png',
        file: 'kortix-mark-light-2560x1440.png',
        bytes: 16656,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-mark-light-1290x2796.png',
        file: 'kortix-mark-light-1290x2796.png',
        bytes: 17532,
      },
    ],
  },
  {
    group: 'product',
    id: 'dither',
    name: 'Dither',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-dither-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-dither-light-5120x2880.png',
        file: 'kortix-dither-light-5120x2880.png',
        bytes: 58385,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-dither-light-1290x2796.png',
        file: 'kortix-dither-light-1290x2796.png',
        bytes: 18464,
      },
    ],
  },
  {
    group: 'product',
    id: 'brandmark',
    name: 'Brandmark',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-brandmark-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-brandmark-light-5120x2880.png',
        file: 'kortix-brandmark-light-5120x2880.png',
        bytes: 183262,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-brandmark-light-1290x2796.png',
        file: 'kortix-brandmark-light-1290x2796.png',
        bytes: 33268,
      },
    ],
  },
  {
    group: 'product',
    id: 'nebula',
    name: 'Pixel Beams',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-nebula-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-nebula-light-5120x2880.png',
        file: 'kortix-nebula-light-5120x2880.png',
        bytes: 61457,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-nebula-light-1290x2796.png',
        file: 'kortix-nebula-light-1290x2796.png',
        bytes: 17265,
      },
    ],
  },
  {
    group: 'product',
    id: 'silk',
    name: 'Silk',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-silk-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-silk-light-5120x2880.jpg',
        file: 'kortix-silk-light-5120x2880.jpg',
        bytes: 144781,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-silk-light-1290x2796.jpg',
        file: 'kortix-silk-light-1290x2796.jpg',
        bytes: 51628,
      },
    ],
  },
  {
    group: 'product',
    id: 'grain',
    name: 'Grain',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-grain-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-grain-light-5120x2880.jpg',
        file: 'kortix-grain-light-5120x2880.jpg',
        bytes: 1107200,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-grain-light-1290x2796.jpg',
        file: 'kortix-grain-light-1290x2796.jpg',
        bytes: 223309,
      },
    ],
  },
  {
    group: 'product',
    id: 'neuro',
    name: 'Neuro',
    theme: 'light',
    preview: '/wallpapers/downloads/kortix-neuro-light-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-neuro-light-5120x2880.jpg',
        file: 'kortix-neuro-light-5120x2880.jpg',
        bytes: 356668,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-neuro-light-1290x2796.jpg',
        file: 'kortix-neuro-light-1290x2796.jpg',
        bytes: 88353,
      },
    ],
  },
  {
    group: 'mark',
    id: 'mark',
    name: 'Kortix Mark',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-mark-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-mark-dark-5120x2880.png',
        file: 'kortix-mark-dark-5120x2880.png',
        bytes: 54945,
      },
      {
        label: '4K',
        width: 3840,
        height: 2160,
        href: '/wallpapers/downloads/kortix-mark-dark-3840x2160.png',
        file: 'kortix-mark-dark-3840x2160.png',
        bytes: 32895,
      },
      {
        label: '1440p',
        width: 2560,
        height: 1440,
        href: '/wallpapers/downloads/kortix-mark-dark-2560x1440.png',
        file: 'kortix-mark-dark-2560x1440.png',
        bytes: 16415,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-mark-dark-1290x2796.png',
        file: 'kortix-mark-dark-1290x2796.png',
        bytes: 17423,
      },
    ],
  },
  {
    group: 'product',
    id: 'dither',
    name: 'Dither',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-dither-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-dither-dark-5120x2880.png',
        file: 'kortix-dither-dark-5120x2880.png',
        bytes: 58313,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-dither-dark-1290x2796.png',
        file: 'kortix-dither-dark-1290x2796.png',
        bytes: 18401,
      },
    ],
  },
  {
    group: 'product',
    id: 'brandmark',
    name: 'Brandmark',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-brandmark-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-brandmark-dark-5120x2880.png',
        file: 'kortix-brandmark-dark-5120x2880.png',
        bytes: 181161,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-brandmark-dark-1290x2796.png',
        file: 'kortix-brandmark-dark-1290x2796.png',
        bytes: 33167,
      },
    ],
  },
  {
    group: 'product',
    id: 'nebula',
    name: 'Pixel Beams',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-nebula-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-nebula-dark-5120x2880.png',
        file: 'kortix-nebula-dark-5120x2880.png',
        bytes: 62830,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-nebula-dark-1290x2796.png',
        file: 'kortix-nebula-dark-1290x2796.png',
        bytes: 17934,
      },
    ],
  },
  {
    group: 'product',
    id: 'silk',
    name: 'Silk',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-silk-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-silk-dark-5120x2880.jpg',
        file: 'kortix-silk-dark-5120x2880.jpg',
        bytes: 162459,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-silk-dark-1290x2796.jpg',
        file: 'kortix-silk-dark-1290x2796.jpg',
        bytes: 45115,
      },
    ],
  },
  {
    group: 'product',
    id: 'grain',
    name: 'Grain',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-grain-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-grain-dark-5120x2880.jpg',
        file: 'kortix-grain-dark-5120x2880.jpg',
        bytes: 842820,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-grain-dark-1290x2796.jpg',
        file: 'kortix-grain-dark-1290x2796.jpg',
        bytes: 168003,
      },
    ],
  },
  {
    group: 'product',
    id: 'neuro',
    name: 'Neuro',
    theme: 'dark',
    preview: '/wallpapers/downloads/kortix-neuro-dark-preview.jpg',
    files: [
      {
        label: '5K',
        width: 5120,
        height: 2880,
        href: '/wallpapers/downloads/kortix-neuro-dark-5120x2880.jpg',
        file: 'kortix-neuro-dark-5120x2880.jpg',
        bytes: 414552,
      },
      {
        label: 'Phone',
        width: 1290,
        height: 2796,
        href: '/wallpapers/downloads/kortix-neuro-dark-1290x2796.jpg',
        file: 'kortix-neuro-dark-1290x2796.jpg',
        bytes: 102084,
      },
    ],
  },
];
